#!/bin/sh
set -e

# /usr/local/bin isn't in the path for cron by default
PATH=$PATH:/usr/local/bin
export PATH

MIRROR_ROOT=/var/lib/govuk_mirror
TMP_ROOT=$(mktemp -d -t govuk_mirror.XXXXX)

cleanup () {
  rm -rf "$LOCK"
  rm -rf "$TMP_ROOT"
}
trap cleanup EXIT

cd "$TMP_ROOT"

DEST="${MIRROR_ROOT}/$(date "+%Y%m%dT%H%M%S")"
logger -i -p user.info -t govuk_update_mirror "Starting to mirror the site"
# Mirror the site
govuk_mirrorer --syslog

if [ ! -d www.gov.uk ] || [ ! "$(du -ks www.gov.uk | awk '{print $1}')" -gt "10000" ]; then
  logger -i -p user.err -t govuk_update_mirror "Mirror appears to have failed (total size < 10MB)"
  logger -i -p user.err -t govuk_update_mirror "Not updating 'current' symlink"
  exit 1
fi

mv www.gov.uk "$DEST"

# Clean up all but the last 7 mirror versions
logger -i -p user.info -t govuk_update_mirror "Cleaning up old directories and logs"
find "$MIRROR_ROOT" -mindepth 1 -maxdepth 1 -type d |
  sort -r |
  tail -n +8 |
  while read dir; do
    rm -rf "$dir"
    if [ -f ${dir}.log ]; then
      rm "${dir}.log"
    fi
  done

# Update symlink to latest version
logger -i -p user.info -t govuk_update_mirror "Updating symlink to newest version"
ln -snf "$DEST" "${MIRROR_ROOT}/current"

# Grab the 503 error page
logger -i -p user.info -t govuk_update_mirror "Grabbing the latest error page"
STATIC_HOSTNAME="static.`cat /etc/govuk/env.d/GOVUK_APP_DOMAIN`"

test -d ${DEST}/error || mkdir ${DEST}/error/
curl -sf https://${STATIC_HOSTNAME}/templates/503.html.erb -o ${DEST}/error/503.html
