# -*- mode: ruby -*-
# vi: set ft=ruby:

#
# NB: please don't use ruby 1.9 syntax in this file until the default system
#     ruby shipping with Mac OS X becomes ruby 1.9
#
DIST_PREFERRED = 'precise'
min_required_vagrant_version = '1.3.0'
DEFAULT_VM_PARAMS = {
  :memory => 1024,
  :cpus => 2,
}
LATEST_BOX_VERSIONS = {
  'lucid'   => '20140430',
  'precise' => '20140430',
}

def common_config(config)
  # vagrant-dns is only supported on OS X
  # https://github.com/BerlinVagrant/vagrant-dns/blob/master/PLATFORM_SUPPORT.md
  if RUBY_PLATFORM =~ /darwin/i
    if Vagrant.has_plugin?("vagrant-dns")
      config.dns.tld = "dev.gov.uk"
      config.dns.patterns = [/^.*dev.gov.uk$/]
    else
      puts "installing vagrant-dns plugin is recommended"
    end
  end

  config.ssh.forward_agent = true

  config
end

def virtual_box_config(config)
  dist = ENV['govuk_dev_dist'] || DIST_PREFERRED
  if dist != DIST_PREFERRED
    puts <<EOS
[warn] Ubuntu version has been overridden with the environment variable
       `govuk_dev_dist` to a version other than "#{DIST_PREFERRED}". Please
       consider unsetting it.

EOS
  end

  virtual_box_box = "govuk_dev_#{dist}64_#{LATEST_BOX_VERSIONS[dist]}"

  config.vm.box = virtual_box_box
  config.vm.box_url = "http://gds-boxes.s3.amazonaws.com/#{virtual_box_box}.box"

  config
end

def load_local_vagrant_file(config)
  # Load local overrides
  if File.exist? 'Vagrantfile.local'
    $stderr.puts "WARNING: Vagrantfile.local is deprecated! Please use Vagrantfile.localconfig instead."
    $stderr.puts ""
  end

  if File.exist? 'Vagrantfile.localconfig'
    instance_eval File.read('Vagrantfile.localconfig'), 'Vagrantfile.localconfig'
  end

  config
end

if Vagrant::VERSION < min_required_vagrant_version
  $stderr.puts "ERROR: Puppet now requires Vagrant version >=#{min_required_vagrant_version}. Please upgrade.\n"
  exit 1
end

Vagrant.configure("2") do |config|
  config = virtual_box_config(config)

  config.vm.provider :vmware_fusion do |vm, override|
    latest_version = LATEST_BOX_VERSIONS['precise']
    box_name = "govuk_dev_precise64_vmware_fusion_#{latest_version}"
    override.vm.box = box_name
    override.vm.box_url = "http://gds-boxes.s3.amazonaws.com/#{box_name}.box"
    vm.vmx["displayName"] = "devvm"
  end

  config.vm.provider :virtualbox do |vm, override|
    vm.customize ["modifyvm", :id, "--rtcuseutc", "on"]
    if override.respond_to? :cache
      override.cache.auto_detect = true
    end
  end

  # Static IP for NFS and DNS
  config.vm.network :private_network, :ip => "10.1.1.254"

  config = common_config(config)

  config.vm.hostname = "development.development"

  config.vm.provision :shell, :inline => "NO_GIT_PULL=1 /var/govuk/puppet/tools/puppet-apply-dev"

  # Use VMWare Fusion native shared folders
  config.vm.provider :vmware_fusion do |vm, override|
    vm.vmx["memsize"] = DEFAULT_VM_PARAMS[:memory]
    vm.vmx["numvcpus"] = DEFAULT_VM_PARAMS[:cpus]
  end

  config.vm.provider :virtualbox do |vm, override|
    vm.customize [ "modifyvm", :id, "--memory", DEFAULT_VM_PARAMS[:memory], "--cpus", DEFAULT_VM_PARAMS[:cpus] ]
  end

  if ENV['VAGRANT_GOVUK_NFS'] == "no"
    config.vm.synced_folder "../..", "/var/govuk"
  else
    config.vm.synced_folder "../..", "/var/govuk", :nfs => true
  end

  # You may want to up the memory / CPUs to get better performance in the VM.
  # Example given below to put in Vagrantfile.localconfig if you want to do so:
  #
  #     config.vm.provider :virtualbox do |vm|
  #       vm.customize [ "modifyvm", :id, "--memory", "2048", "--cpus", "4" ]
  #     end
  #     config.vm.provider :vmware_fusion do |vm|
  #       vm.vmx["memsize"] = "2048"
  #       vm.vmx["numvcpus"] = "4"
  #     end

  config = load_local_vagrant_file(config)
end
