#!/usr/bin/env bash
set -eu
APPLICATION=$1

function exit_unknown() {
    echo "UNKNOWN: Unable to determine expected workers"
    echo
    echo "Please try running check and subsequent commands manually."
    exit 3
}
trap exit_unknown ERR

CONFIG_FILES="/var/apps/${APPLICATION}/config/unicorn.rb /etc/govuk/unicorn.rb"
EXPECTED_WORKERS=""

cd /var/apps/${APPLICATION}/
for CONFIG_FILE in $CONFIG_FILES; do
    [ -f $CONFIG_FILE ] || continue

    EXPECTED_WORKERS=$(govuk_setenv ${APPLICATION} env GOVUK_APP_LOGROOT=/tmp \
        bundle exec ruby \
        -e 'require "unicorn"; puts Unicorn::Configurator.new(:config_file => "'${CONFIG_FILE}'")[:worker_processes]' \
        2>/dev/null)
done

# Bail if not an integer.
[[ $EXPECTED_WORKERS != *[!0-9]* ]] || exit_unknown

set +e
/usr/lib/nagios/plugins/check_procs -a "unicorn worker" --ereg-argument-array="/var/run/${APPLICATION}/app.pid" -c 1: -w ${EXPECTED_WORKERS}:${EXPECTED_WORKERS}
