#!/usr/bin/env bash
APPLICATION=$1
# Check for the application config
if [ -e /var/apps/${APPLICATION}/config/unicorn.rb ]; then
    cd /var/apps/${APPLICATION}/
    EXPECTED_WORKERS=`govuk_setenv ${APPLICATION} env GOVUK_APP_LOGROOT=/tmp bundle exec ruby -r unicorn -e 'puts Unicorn::Configurator.new(:config_file => "config/unicorn.rb")[:worker_processes]'`
elif [ -e /etc/govuk/unicorn.rb ]; then
    cd /var/apps/${APPLICATION}/
    EXPECTED_WORKERS=`govuk_setenv ${APPLICATION} env GOVUK_APP_LOGROOT=/tmp bundle exec ruby -r unicorn -e 'puts Unicorn::Configurator.new(:config_file => "/etc/govuk/unicorn.rb")[:worker_processes]'`
else
    EXPECTED_WORKERS=4
fi
# Catchall just in case any of the above return no value
if [ "$EXPECTED_WORKERS" == "" ]; then
    EXPECTED_WORKERS=4
fi
/usr/lib/nagios/plugins/check_procs -a "unicorn worker" --ereg-argument-array="${APPLICATION}" -c 1: -w $EXPECTED_WORKERS
