#!/bin/sh
cd /var/govuk/puppet

# Filter warnings about 'storeconfigs' not being set -- we don't currently
# attempt to test stored config configuration on the dev vm
exec sudo RUBYOPT="-W0" puppet apply manifests/site.pp "$@" | egrep -v "warning:.+storeconfigs"
