#!/bin/bash

# Re-exec self with sudo if not root.
if [ "$(id -u)" -ne "0" ]; then
  exec sudo "$BASH_SOURCE" "$@"
fi

# Prepend to PATH for when:
#   - rbenv ruby shim is in /usr/lib/rbenv/shims/ruby
#   - Cron runs with `PATH=/usr/bin:bin`
PATH="/usr/lib/rbenv/shims:${PATH}"

RBENV_VERSION=1.9.3 puppet agent --onetime --no-daemonize "$@"
