source "http://rubygems.org"

gem "rake"
gem "puppet-lint"
gem "puppet", "2.7.19"
gem "rspec-puppet"
gem "parallel_tests"
gem "parallel"
gem "librarian-puppet"
gem "webmock"
gem "mechanize"
gem "spidey"
