#!/usr/bin/env bash
set -eu
APPLICATION=$1

function exit_unknown() {
    echo "UNKNOWN: Unable to determine expected workers"
    echo
    echo "Please try running check and subsequent commands manually."
    exit 3
}
trap exit_unknown ERR

EXPECTED_WORKERS=""
if [ -f "/var/apps/${APPLICATION}/config/unicorn.rb" ]; then
    CONFIG_FILE="config/unicorn.rb"
else
    CONFIG_FILE="/etc/govuk/unicorn.rb"
fi

cd /var/apps/${APPLICATION}/
EXPECTED_WORKERS=$(env -i /usr/local/bin/govuk_setenv ${APPLICATION} \
    env HOME=/tmp GOVUK_APP_LOGROOT=/tmp bundle exec ruby \
    -e 'require "unicorn"; puts Unicorn::Configurator.new(:config_file => "'${CONFIG_FILE}'")[:worker_processes]' \
    2>/dev/null)

# Bail if not an integer.
[[ $EXPECTED_WORKERS != *[!0-9]* ]] || exit_unknown

set +e
trap - ERR
/usr/lib/nagios/plugins/check_procs -a "unicorn worker" --ereg-argument-array="/var/run/${APPLICATION}/app.pid" -c 1: -w ${EXPECTED_WORKERS}:${EXPECTED_WORKERS}
