#!/usr/bin/env bash
set -eu
APPLICATION=$1

function exit_unknown() {
    local message=${1-"Unable to determine expected ruby version"}
    echo "UNKNOWN: ${message}"
    echo
    echo "Please try running check and subsequent commands manually."
    exit 3
}
trap exit_unknown ERR

RUBY_VERSION_FILE=/var/apps/${APPLICATION}/.ruby-version
[ -f $RUBY_VERSION_FILE ] || exit_unknown "${RUBY_VERSION_FILE} not found"

EXPECTED_RUBY=/usr/lib/rbenv/versions/$(grep "^[^#]" ${RUBY_VERSION_FILE})/bin/ruby

UNICORN_PID=$(cat /var/run/${APPLICATION}/app.pid)
# Bail if not an integer.
[[ $UNICORN_PID != *[!0-9]* ]] || exit_unknown "Couldn't read application PID"

UNICORN_RUBY=$(readlink /proc/${UNICORN_PID}/exe)

if [ $UNICORN_RUBY == $EXPECTED_RUBY ]; then
  echo "OK"
  exit 0
else
  echo "WARNING: Ruby version mismatch: got ${UNICORN_RUBY}, expected ${EXPECTED_RUBY}"
  exit 1
fi
