#!/usr/bin/env ruby

# es_dump
# -------
# export all Elasticsearch indexes which have aliases to zip archives
#
# USAGE:
# es_dump <instance url> <save path>
#

require 'rubygems'
require 'net/http'
require 'logger'
require 'json'
require 'es_dump_restore'

logger = Logger.new(STDOUT)

host = ARGV[0]
directory = ARGV[1] || "/var/es_dump"

uri = URI.join(host, "/_aliases")

logger.info "Connecting to Elasticsearch on #{host}"
res = Net::HTTP.get_response(uri)

raise "Could not connect to Elasticsearch on #{uri}. Status code: #{res.code}" unless res.code == '200'

indexes = JSON.parse(res.body)
aliases = indexes.map {|k,i| i['aliases'].keys }.flatten

logger.info "Discovered #{aliases.size} aliases from #{host}"

aliases.each_with_index do |index_name,i|
  logger.info "Requesting #{host}/#{index_name} (#{i+1} of #{aliases.size})"
  EsDumpRestore::App.new.dump(host, index_name, File.join(directory, "#{index_name}.zip"))
end
