class nagios::client::checks {
  @@nagios::host { "${::govuk_class}-${::hostname}":
    hostalias => $::fqdn,
    address   => $::ipaddress,
  }

  @@nagios::check { "check_ping_${::hostname}":
    check_command       => 'check_ping!100.0,20%!500.0,60%',
    host_name           => "${::govuk_class}-${::hostname}",
    notification_period => '24x7',
    service_description => "check ping for ${::govuk_class}-${::hostname}",
  }

  @@nagios::check { "check_disk_${::hostname}":
    check_command       => 'check_nrpe_1arg!check_disk',
    service_description => "check disk on ${::govuk_class}-${::hostname}",
    host_name           => "${::govuk_class}-${::hostname}",
  }

  @@nagios::check { "check_users_${::hostname}":
    check_command       => 'check_nrpe_1arg!check_users',
    service_description => "check users on ${::govuk_class}-${::hostname}",
    host_name           => "${::govuk_class}-${::hostname}",
  }

  @@nagios::check { "check_zombies_${::hostname}":
    check_command       => 'check_nrpe_1arg!check_zombie_procs',
    service_description => "check for zombies on ${::govuk_class}-${::hostname}",
    host_name           => "${::govuk_class}-${::hostname}",
  }

  @@nagios::check { "check_procs_${::hostname}":
    check_command       => 'check_nrpe_1arg!check_total_procs',
    service_description => "check procs on ${::govuk_class}-${::hostname}",
    host_name           => "${::govuk_class}-${::hostname}",
  }

  @@nagios::check { "check_load_${::hostname}":
    check_command       => 'check_nrpe_1arg!check_load',
    service_description => "check load on ${::govuk_class}-${::hostname}",
    host_name           => "${::govuk_class}-${::hostname}",
  }

  @@nagios::check { "check_ssh_${::hostname}":
    check_command       => 'check_ssh',
    service_description => "check ssh access to ${::govuk_class}-${::hostname}",
    host_name           => "${::govuk_class}-${::hostname}",
  }

  @@nagios::check { "check_puppet_${::hostname}":
    check_command       => 'check_nrpe_1arg!check_puppet',
    service_description => "Check puppet has run recently on ${::govuk_class}-${::hostname}",
    host_name           => "${::govuk_class}-${::hostname}",
  }

  file { '/.check_rw_rootfs':
    content => "This file was generated by puppet. It is present so the nagios user can check if the root filesystem is readonly.\n",
    owner   => 'nagios',
    group   => 'nagios',
    mode    => '0644',
  }

  file { '/usr/lib/nagios/plugins/check_rw_rootfs':
    owner   => 'nagios',
    group   => 'nagios',
    mode    => '0755',
    source  => 'puppet:///nagios/usr/lib/nagios/plugins/check_rw_rootfs',
    require => Package['nagios-nrpe-plugin'],
  }

  @@nagios::check { "check_rw_rootfs_${::hostname}":
    check_command       => 'check_nrpe_1arg!check_rw_rootfs',
    service_description => 'Check that root filesystem is writable',
    host_name           => "${::govuk_class}-${::hostname}",
  }
}
