class nagios::client::check_rw_rootfs {
  file { '/.check_rw_rootfs':
    content => "This file was generated by puppet. It is present so the nagios user can check if the root filesystem is readonly.\n",
    owner   => 'nagios',
    group   => 'nagios',
    mode    => '0644',
  }

  file { '/usr/lib/nagios/plugins/check_rw_rootfs':
    owner   => 'nagios',
    group   => 'nagios',
    mode    => '0755',
    source  => 'puppet:///nagios/usr/lib/nagios/plugins/check_rw_rootfs',
    require => Package['nagios-nrpe-plugin'],
  }

  @@nagios::check { "check_rw_rootfs_${::hostname}":
    check_command       => 'check_nrpe_1arg!check_rw_rootfs',
    service_description => 'Check that root filesystem is writable',
    host_name           => "${::govuk_class}-${::hostname}",
  }
}