---

_: &offsite_gpg_key 'BF7CE69AB6DA000D8CC3841EA98D1837723776D7'

app_domain: 'publishing.service.gov.uk'

# Staging/production will not have separate internal load balancers until migrated to AWS
app_domain_internal: 'publishing.service.gov.uk'

backup::offsite::jobs:
  'govuk-datastores-s3':
    sources:
      - '/data/backups/*/var/lib/automongodbbackup/latest'
      - '/data/backups/*/var/lib/automysqlbackup/latest.tbz2'
      - '/data/backups/archived'
    destination: 's3://s3-eu-west-1.amazonaws.com/govuk-offsite-backups-production/govuk-datastores/'
    aws_access_key_id: "%{hiera('backup::offsite::job::aws_access_key_id')}"
    aws_secret_access_key: "%{hiera('backup::offsite::job::aws_secret_access_key')}"
    hour: 8,
    minute: 13,
    gpg_key_id: *offsite_gpg_key
  'govuk-graphite-s3':
    sources: '/data/backups/*/opt/graphite/storage/whisper'
    destination: 's3://s3-eu-west-1.amazonaws.com/govuk-offsite-backups-production/backup-graphite/'
    aws_access_key_id: "%{hiera('backup::offsite::job::aws_access_key_id')}"
    aws_secret_access_key: "%{hiera('backup::offsite::job::aws_secret_access_key')}"
    weekday: 6
    hour: 8,
    minute: 13,
    s3_use_multiprocessing: true
    s3_multipart_max_procs: 4
    # No encryption because of size and sensitivity

base::shell::shell_prompt_string: 'production'
base::supported_kernel::enabled: true

environment_ip_prefix: '10.3'

govuk::apps::asset_manager::aws_s3_bucket_name: 'govuk-assets-production'
govuk::apps::asset_manager::aws_region: 'eu-west-1'
govuk::apps::content_publisher::aws_s3_bucket: "govuk-production-content-publisher-activestorage"
govuk::apps::content_publisher::google_tag_manager_auth: "sxvBI4QvwgTRX5e76vdIHA"
govuk::apps::content_publisher::google_tag_manager_id: "GTM-NQXC4TG"
govuk::apps::content_publisher::google_tag_manager_preview: "env-2"
govuk::apps::content_publisher::govuk_notify_template_id: "e00e89f5-b622-4dcb-8f30-e6c70231a940"
govuk::apps::contacts::enabled: false
govuk::apps::content_publisher::enabled: false
govuk::apps::government-frontend::cpu_warning: 200
govuk::apps::government-frontend::cpu_critical: 300
govuk::apps::hmrc_manuals_api::publish_topics: false
govuk::apps::publisher::fact_check_address_format: 'factcheck+production-{id}@alphagov.co.uk'
govuk::apps::publisher::fact_check_reply_to_id: '792923cb-fa07-4dce-a4c5-e6320bd19c17'
govuk::apps::publisher::fact_check_reply_to_address: 'factcheck+production@alphagov.co.uk'
govuk::apps::publisher::email_group_dev: 'govuk-dev@digital.cabinet-office.gov.uk'
govuk::apps::publisher::email_group_business: 'publisher-alerts-business@digital.cabinet-office.gov.uk'
govuk::apps::publisher::email_group_citizen: 'publisher-alerts-citizen@digital.cabinet-office.gov.uk'
govuk::apps::publisher::email_group_force_publish_alerts: 'mainstream-force-publishing-alerts@digital.cabinet-office.gov.uk'
govuk::apps::publisher::govuk_notify_template_id: "e00e89f5-b622-4dcb-8f30-e6c70231a940"
govuk::apps::search_admin::govuk_notify_template_id: "e00e89f5-b622-4dcb-8f30-e6c70231a940"
govuk::apps::service_manual_publisher::govuk_notify_template_id: "e00e89f5-b622-4dcb-8f30-e6c70231a940"
govuk::apps::short_url_manager::govuk_notify_template_id: 'e00e89f5-b622-4dcb-8f30-e6c70231a940'
govuk::apps::specialist_publisher::aws_region: 'eu-west-1'
govuk::apps::specialist_publisher::aws_s3_bucket_name: 'govuk-production-specialist-publisher-csvs'
govuk::apps::specialist_publisher::enabled: false
govuk::apps::specialist_publisher::govuk_notify_template_id: "e00e89f5-b622-4dcb-8f30-e6c70231a940"
govuk::apps::travel_advice_publisher::enable_email_alerts: false
govuk::apps::travel_advice_publisher::enable_procfile_worker: false
govuk::apps::whitehall::govuk_notify_template_id: "e00e89f5-b622-4dcb-8f30-e6c70231a940"

govuk::apps::contacts::ensure: 'absent'
govuk::apps::collections_publisher::ensure: 'absent'
govuk::apps::content_publisher::ensure: 'absent'
govuk::apps::content_tagger::ensure: 'absent'
govuk::apps::hmrc_manuals_api::ensure: 'absent'
govuk::apps::manuals_publisher::ensure: 'absent'
govuk::apps::maslow::ensure: 'absent'
govuk::apps::publisher::ensure: 'absent'
govuk::apps::search_admin::ensure: 'absent'
govuk::apps::service_manual_publisher::ensure: 'absent'
govuk::apps::short_url_manager::ensure: 'absent'
govuk::apps::specialist_publisher::ensure: 'absent'
govuk::apps::travel_advice_publisher::ensure: 'absent'

govuk::apps::content_tagger::override_search_location: 'https://search-api.production.govuk.digital'
govuk::apps::hmrc_manuals_api::override_search_location: 'https://search-api.production.govuk.digital'
govuk::apps::search_admin::override_search_location: 'https://search-api.production.govuk.digital'

govuk::deploy::actionmailer_enable_delivery: true

govuk::deploy::aws_ses_smtp_host: 'email-smtp.us-east-1.amazonaws.com'
govuk::deploy::config::errbit_environment_name: 'production'
govuk::deploy::config::website_root: 'https://www.gov.uk'
govuk::deploy::setup::ssh_keys:
  jenkins_production_carrenza: 'AAAAB3NzaC1yc2EAAAADAQABAAACAQCfPjubgzCkZo1aTPlkgeXb1eh3IonRBRptx0qLMCjOV+e+M8uRAT/Xx3ydJYPd7sOgZDyx2xjSGb7Eefau0jSUAcMD1Xd01SXWBQPJRDfPmQLrdbM0xxOFH8nft39uo4Mz6ccZc34xrudL6q/urp732HZHYwltnNnbk9h58n1QIhemRtN3u9RrSSOILqw/F42S6Aj8lZ1v/DGgfc6F5pKyJ7TByHL1RlqwpZHbEjYYuvK0ZJJsKPlyVPbNDsX7UEYWwbpPsFs9LPvCC6epmj+7Lv25bTU8rKK8J3rNWa1FybpWS0VXbF/+mrLjtT0/vwvbwUzsjK6dSUsbEsBEn+cOqomxCYkLjMzUy1+ReYAh6+CjmzutPs1g4OjQRel2ONprhPTEsNUu+oNObnGDOUpzHK10ntAZxguA4QEUmOBBWfxuQhmJO60/b1zedCcc7MR8e9S0y4jtpXa8GBCe40+napArZTW9QXlHLWz+khkYQfO107Q+z1QaLFojdcrHlUfpqAc6DtVJQu7tsBt2vXTn0qq6mU5Eg6UY+X1l/3gWdFS3ZEvCUoGK6bLU3i50jZ1xsFogFFfvSux46S1DYW2Fk8a/2IBBdcQcL1YoM73jiAQgpU8Vs50wtk4mWhK1yBaMYmMAeL7mKFbJla7SjTAwaDdo5uezyrJlbZxqTb/Y3w=='

govuk_bouncer::gor::enabled: true
govuk_bouncer::gor::target: '195.225.216.149'

govuk_jenkins::config::banner_colour_background: '#df3034'
govuk_jenkins::config::banner_colour_text: 'white'
govuk_jenkins::config::banner_string: 'Carrenza PRODUCTION'
govuk_jenkins::config::theme_colour: '#df3034'
govuk_jenkins::config::theme_text_colour: 'white'
govuk_jenkins::config::theme_environment_name: 'Production'

govuk_jenkins::job_builder::environment: 'production'

govuk_jenkins::jobs::network_config_deploy::environments:
  - 'carrenza-production'
  - 'carrenza-production-dr'
  - 'skyscape-production'

govuk_jenkins::jobs::signon_cron_rake_tasks::configure_jobs: true
govuk_jenkins::jobs::signon_cron_rake_tasks::rake_oauth_access_grants_delete_expired_frequency: '0 12 * * 0'
govuk_jenkins::jobs::signon_cron_rake_tasks::rake_organisations_fetch_frequency: '0 3 * * *'
govuk_jenkins::jobs::signon_cron_rake_tasks::rake_users_suspend_inactive_frequency: '0 4 * * *'
govuk_jenkins::jobs::signon_cron_rake_tasks::rake_users_send_suspension_reminders_frequency: '0 6 * * *'

govuk_jenkins::jobs::deploy_dns::gce_client_name: 'govuk-dns-deploy'
govuk_jenkins::jobs::deploy_dns::gce_project_id: 'govuk-production'

govuk_jenkins::ssh_key::public_key: 'AAAAB3NzaC1yc2EAAAADAQABAAACAQCfPjubgzCkZo1aTPlkgeXb1eh3IonRBRptx0qLMCjOV+e+M8uRAT/Xx3ydJYPd7sOgZDyx2xjSGb7Eefau0jSUAcMD1Xd01SXWBQPJRDfPmQLrdbM0xxOFH8nft39uo4Mz6ccZc34xrudL6q/urp732HZHYwltnNnbk9h58n1QIhemRtN3u9RrSSOILqw/F42S6Aj8lZ1v/DGgfc6F5pKyJ7TByHL1RlqwpZHbEjYYuvK0ZJJsKPlyVPbNDsX7UEYWwbpPsFs9LPvCC6epmj+7Lv25bTU8rKK8J3rNWa1FybpWS0VXbF/+mrLjtT0/vwvbwUzsjK6dSUsbEsBEn+cOqomxCYkLjMzUy1+ReYAh6+CjmzutPs1g4OjQRel2ONprhPTEsNUu+oNObnGDOUpzHK10ntAZxguA4QEUmOBBWfxuQhmJO60/b1zedCcc7MR8e9S0y4jtpXa8GBCe40+napArZTW9QXlHLWz+khkYQfO107Q+z1QaLFojdcrHlUfpqAc6DtVJQu7tsBt2vXTn0qq6mU5Eg6UY+X1l/3gWdFS3ZEvCUoGK6bLU3i50jZ1xsFogFFfvSux46S1DYW2Fk8a/2IBBdcQcL1YoM73jiAQgpU8Vs50wtk4mWhK1yBaMYmMAeL7mKFbJla7SjTAwaDdo5uezyrJlbZxqTb/Y3w=='

govuk_mysql::server::innodb_buffer_pool_size_proportion: '0.5'

govuk::node::s_api_lb::api_servers:
  - "api-1.api"
  - "api-2.api"

govuk::node::s_apt::real_ip_header: 'True-Client-Ip'
govuk::node::s_backend_lb::aws_egress_nat_ips:
  - '34.246.209.74'
  - '34.253.57.8'
  - '18.202.136.43'
govuk::node::s_backend_lb::backend_servers:
  - 'backend-1.backend'
  - 'backend-2.backend'
  - 'backend-3.backend'
govuk::node::s_backend_lb::whitehall_backend_servers:
  - 'whitehall-backend-1.backend'
  - 'whitehall-backend-2.backend'
  - 'whitehall-backend-3.backend'
  - 'whitehall-backend-4.backend'
govuk::node::s_backend_lb::whitehall_frontend_servers:
  - 'whitehall-frontend-1.frontend'
  - 'whitehall-frontend-2.frontend'
  - 'whitehall-frontend-3.frontend'
govuk::node::s_backend_lb::perfplat_public_app_domain: 'performance.service.gov.uk'

govuk::node::s_backup::offsite_backups: true

govuk::node::s_cache::real_ip_header: 'True-Client-Ip'
govuk::node::s_frontend_lb::whitehall_frontend_servers:
  - 'whitehall-frontend-1.frontend'
  - 'whitehall-frontend-2.frontend'
  - 'whitehall-frontend-3.frontend'
govuk::node::s_monitoring::enable_fastly_metrics: true
govuk::node::s_mysql_backup::s3_bucket_name: 'govuk-mysql-xtrabackups-production'
govuk::node::s_mysql_master::s3_bucket_name: "%{hiera('govuk::node::s_mysql_backup::s3_bucket_name')}"

hosts::production::ip_api_lb: '10.3.4.254'
hosts::production::ip_backend_lb: '10.3.3.254'
hosts::production::ip_bouncer: '37.26.90.219'
hosts::production::ip_draft_api_lb: '10.3.4.253'
hosts::production::ip_frontend_lb: '10.3.2.254'

hosts::production::api::hosts:
  api-1:
    ip: '10.3.4.16'
  api-2:
    ip: '10.3.4.17'
  api-lb-1:
    ip: '10.3.4.101'
  api-lb-2:
    ip: '10.3.4.102'
  api-mongo-1:
    ip: '10.3.4.21'
  api-mongo-2:
    ip: '10.3.4.22'
  api-mongo-3:
    ip: '10.3.4.23'
  api-mongo-4:
    ip: '10.3.12.21'
  performance-mongo-1:
    ip: '10.3.4.31'
  performance-mongo-2:
    ip: '10.3.4.32'
  performance-mongo-3:
    ip: '10.3.4.33'
  performance-mongo-4:
    ip: '10.3.12.31'

hosts::production::backend::app_hostnames:
  - 'canary-backend'
  - 'docs'
  - 'signon'

hosts::production::backend::hosts:
  asset-master-1:
    ip: '10.3.3.20'
    legacy_aliases:
      - "asset-master-1.%{hiera('app_domain')}"
      - 'asset-master'
      - "asset-master.%{hiera('app_domain')}"
  asset-slave-1:
    ip: '10.3.3.21'
    legacy_aliases:
      - "asset-slave-1.%{hiera('app_domain')}"
      - 'asset-slave'
      - "asset-slave.%{hiera('app_domain')}"
  asset-slave-2:
    ip: '10.3.11.21'
  backend-1:
    ip: '10.3.3.2'
  backend-2:
    ip: '10.3.3.3'
  backend-3:
    ip: '10.3.3.4'
  backend-lb-1:
    ip: '10.3.3.101'
  backend-lb-2:
    ip: '10.3.3.102'
  docker-backend-1:
    ip: '10.3.3.111'
  docker-backend-2:
    ip: '10.3.3.112'
  mongo-1:
    ip: '10.3.3.6'
    service_aliases:
      - 'mongodb'
  mongo-2:
    ip: '10.3.3.7'
  mongo-3:
    ip: '10.3.3.8'
  mongo-4:
    ip: '10.3.11.6'
  mysql-backup-1:
    ip: '10.3.3.93'
    legacy_aliases:
      - 'backup.mysql'
  mysql-master-1:
    ip: '10.3.3.90'
    legacy_aliases:
      - 'master.mysql'
      - "mysql.backend.%{hiera('app_domain')}"
  mysql-slave-1:
    ip: '10.3.3.91'
    legacy_aliases:
      - 'slave.mysql'
  mysql-slave-2:
    ip: '10.3.3.92'
  mysql-slave-3:
    ip: '10.3.11.91'
  postgresql-primary-1:
    ip: '10.3.3.12'
  postgresql-standby-1:
    ip: '10.3.3.13'
  postgresql-standby-2:
    ip: '10.3.11.13'
  rabbitmq-1:
    ip: '10.3.3.70'
  rabbitmq-2:
    ip: '10.3.3.71'
  rabbitmq-3:
    ip: '10.3.3.72'
  redis-1:
    ip: '10.3.3.50'
  redis-2:
    ip: '10.3.3.51'
  whitehall-backend-1:
    ip: '10.3.3.25'
  whitehall-backend-2:
    ip: '10.3.3.26'
  whitehall-backend-3:
    ip: '10.3.3.27'
  whitehall-backend-4:
    ip: '10.3.3.28'

hosts::production::frontend::hosts:
  whitehall-frontend-1:
    ip: '10.3.2.5'
  whitehall-frontend-2:
    ip: '10.3.2.6'
  whitehall-frontend-3:
    ip: '10.3.2.10'
  frontend-lb-1:
    ip: '10.3.2.101'
  frontend-lb-2:
    ip: '10.3.2.102'

hosts::production::management::hosts:
  jenkins-1:
    ip: '10.3.0.3'
    legacy_aliases:
      - "deploy.%{hiera('app_domain')}"
  puppetmaster-1:
    ip: '10.3.0.6'
    legacy_aliases:
      - 'puppet'
    service_aliases:
      - 'puppet'
      - 'puppetdb'
      - "puppetmaster-2.%{hiera('app_domain')}"
  puppetmaster-2:
    ip: '10.3.0.6'
  monitoring-1:
    ip: '10.3.0.20'
    legacy_aliases:
      - 'monitoring'
      - "grafana.%{hiera('app_domain')}"
      - "alert.%{hiera('app_domain')}"
    service_aliases:
      - 'alert'
      - 'monitoring'
  graphite-1:
    ip: '10.3.0.22'
    legacy_aliases:
      - "graphite.%{hiera('app_domain')}"
    service_aliases:
      - 'graphite'
  backup-1:
    ip: '10.3.0.50'
  apt-1:
    ip: '10.3.0.75'
    legacy_aliases:
      - "%{hiera('apt_mirror_hostname')}"
    service_aliases:
      - 'apt'
      - 'gemstash'
  docker-management-1:
    ip: '10.3.0.80'
    service_aliases:
      - 'etcd'
  jumpbox-1:
    ip: '10.3.0.100'
  jumpbox-2:
    ip: '10.3.0.200'

hosts::production::redirector::hosts:
  bouncer-1:
    ip: '10.3.5.4'
  bouncer-2:
    ip: '10.3.5.5'
  bouncer-3:
    ip: '10.3.5.6'
  bouncer-4:
    ip: '10.3.13.4'
  bouncer-5:
    ip: '10.3.13.5'
  bouncer-6:
    ip: '10.3.13.6'

monitoring::checks::aws_origin_domain: "production.govuk.digital"
monitoring::checks::aws_iam_key::enabled: false
monitoring::checks::aws_iam_key::region: 'eu-west-1'
monitoring::checks::aws_iam_key::max_aws_iam_key_age: 90
monitoring::checks::smokey::environment: 'production'
monitoring::checks::smokey::ensure: 'absent'
monitoring::contacts::notify_pager: true
monitoring::contacts::notify_slack: true
monitoring::contacts::slack_channel: '#govuk-alerts'
monitoring::contacts::slack_username: 'Production (Carrenza)'
monitoring::edge::enabled: true
monitoring::uptime_collector::environment: 'production'
monitoring::vpn_gateways::endpoints:
  vpn_gateway_api_dr:
    address: "%{hiera('environment_ip_prefix')}.12.1"
  vpn_gateway_backend_dr:
    address: "%{hiera('environment_ip_prefix')}.11.1"
  vpn_gateway_redirector_dr:
    address: "%{hiera('environment_ip_prefix')}.13.1"
  vpn_gateway_router_dr:
    address: "%{hiera('environment_ip_prefix')}.9.1"

postfix::smarthost:
  - 'email-smtp.us-east-1.amazonaws.com:587'
  - 'ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com:587'
postfix::rewrite_mail_domain: 'digital.cabinet-office.gov.uk'
postfix::rewrite_mail_list: 'machine.email.carrenza'

mongodb::s3backup::backup::s3_bucket: 'govuk-mongodb-backup-s3-production'
mongodb::s3backup::backup::s3_bucket_daily: 'govuk-mongodb-backup-s3-daily-production'
