---
app_domain: 'staging.publishing.service.gov.uk'

base::supported_kernel::enabled: true

govuk::apps::content_register::db::backend_ip_range: '10.2.3.0/24'
govuk::apps::email_alert_api::db::backend_ip_range: '10.2.3.0/24'
govuk::apps::email_alert_monitor::db::backend_ip_range: '10.2.3.0/24'
govuk::apps::errbit::errbit_email_from: 'govuk-winston+errbit-staging@digital.cabinet-office.gov.uk'
govuk::apps::policy_publisher::db::backend_ip_range: '10.2.3.0/24'
govuk::apps::publicapi::backdrop_host: 'www.staging.performance.service.gov.uk'
govuk::apps::publishing_api::db::backend_ip_range: '10.2.3.0/24'
govuk::apps::service_manual_publisher::db::backend_ip_range: '10.2.3.0/24'
govuk::apps::sidekiq_monitoring::enabled: true
govuk::apps::stagecraft::postgresql_db::api_ip_range: '10.2.4.0/24'
govuk::apps::support_api::db::backend_ip_range: '10.2.3.0/24'
govuk::apps::transition::postgresql_db::backend_ip_range: '10.2.3.0/24'
govuk::apps::url_arbiter::db::backend_ip_range: '10.2.3.0/24'

govuk::deploy::aws_ses_smtp_host: 'email-smtp.eu-west-1.amazonaws.com'
govuk::deploy::config::errbit_environment_name: 'staging'
govuk::deploy::setup::ssh_keys:
    jenkins_staging_carrenza: 'AAAAB3NzaC1yc2EAAAADAQABAAABAQC7aWtyeQTBcNav3RwyFDacYaO8Ab9wX5rqXKqgd3JlWzr95i7IlCsXSovboqHw3h1J6FrCDxafbhLWJ0lFHlNdGLgX9AysZgMLJCfaJ88RTbWnCyXvTcJBHKHhRkdCrfdXGobeiIOFTOCR2zm9E7EiUXLivgBDfWulo6on4wiyQcGzsMret8SbqUYDi+BBvOGUqun01L/dMIa5DIrPSe9mJ96jXk41x8PI96jZa0XlAkZuiUP2RnZDFBDYIOiN1MaPdcgtBp81Tjo9m41GdfTztZ8hJ+9HicBjCZFH14/zK8Hk9UNZafG6mGtTvn45InF3w2z5qtXamV7s9b/V3xr9'
    jenkins_production_carrenza: 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDvfe5R+1OKwEBQqQIECW4k4LaFrTZedFWK5pzSAM6QxpQtCbKau4ZnD1ToPLX/IGYnW9m/2QfTQoBUtJvERjJvvGs7Wy6I+nKpr4gBVuDiFWilaXZ0rhdlnfU+r/DvFwRR5qjt7pewAlzdcDKp/NAa9BPIYL+YSX4XAZE0b8YMGxeJFQ4sd4CloTJxiUF2F1t2OObXhdQfp2BKtjHMwqClxW6ZthjKcqT4tBkZfo/gzd0TG0FmykNH+tG5q9Y7oxxe52TfJudIobSLgbmXOoEuSNjlwgktb6B+K3J08txo7dG0HrDdamSDTQxXVhn1K1re3cMJokV0N59hazHh7+vx'

govuk_jenkins::config::banner_colour_background: '#ffbf47'
govuk_jenkins::config::banner_colour_text: 'black'
govuk_jenkins::config::banner_string: 'Carrenza STAGING'
govuk_jenkins::config::manage_config: true

govuk_jenkins::config::admins:
  - alexmuller
  - bobwalker
  - ci_alphagov
  - joshmyers
  - mattbostock
  - paulmartin

govuk_jenkins::config::users:
  - alexmuller
  - alextomlins
  - bobwalker
  - bradleywright
  - danielroseman
  - davidsingleton
  - deploy
  - elliotcrosbymccullough
  - jakebenilov
  - jamiecobbett
  - jennyduckett
  - joshmyers
  - kushalpisavadia
  - mattbostock
  - paulmartin
  - richardboulton
  - robyoung
  - stevelaing
  - timothymower
  - tombooth
  - tommypalmer

govuk_jenkins::job_builder::manage_jobs: true
govuk_jenkins::job_builder::jobs:
  - govuk_jenkins::job::staging::data_sync_complete
  - govuk_jenkins::job::deploy_router_data
  - govuk_jenkins::job::run_whitehall_data_migrations
  - govuk_jenkins::job::service_manual_rebuild_search_index
  - govuk_jenkins::job::deploy_app
  - govuk_jenkins::job::deploy_cdn
  - govuk_jenkins::job::deploy_licensify
  - govuk_jenkins::job::deploy_puppet
  - govuk_jenkins::job::govuk_cdn_nightly_2xx_status_collection
  - govuk_jenkins::job::launch_vms
  - govuk_jenkins::job::network_config_deploy
  - govuk_jenkins::job::passive_checks
  - govuk_jenkins::job::performance_platform_smokey
  - govuk_jenkins::job::smokey
  - govuk_jenkins::job::smokey_deploy
govuk_jenkins::job_builder::environment: 'staging'

govuk_jenkins::job::network_config_deploy::environments:
  - 'carrenza-staging'
  - 'carrenza-staging-dr'
  - 'skyscape-staging'

govuk_jenkins::job::performance_platform_smokey::pp_full_app_domain: "staging.performance.service.gov.uk"
govuk_jenkins::job::performance_platform_smokey::pp_app_domain: "staging.performance.service.gov.uk"

govuk_jenkins::job::staging::data_sync_complete::signon_domain_old: publishing.service.gov.uk
govuk_jenkins::job::staging::data_sync_complete::signon_domain_new: staging.publishing.service.gov.uk
govuk_jenkins::job::staging::data_sync_complete::pp_signon_domain_old: performance.service.gov.uk
govuk_jenkins::job::staging::data_sync_complete::pp_signon_domain_new: staging.performance.service.gov.uk


govuk_jenkins::ssh_key::public_key: 'AAAAB3NzaC1yc2EAAAADAQABAAABAQC7aWtyeQTBcNav3RwyFDacYaO8Ab9wX5rqXKqgd3JlWzr95i7IlCsXSovboqHw3h1J6FrCDxafbhLWJ0lFHlNdGLgX9AysZgMLJCfaJ88RTbWnCyXvTcJBHKHhRkdCrfdXGobeiIOFTOCR2zm9E7EiUXLivgBDfWulo6on4wiyQcGzsMret8SbqUYDi+BBvOGUqun01L/dMIa5DIrPSe9mJ96jXk41x8PI96jZa0XlAkZuiUP2RnZDFBDYIOiN1MaPdcgtBp81Tjo9m41GdfTztZ8hJ+9HicBjCZFH14/zK8Hk9UNZafG6mGtTvn45InF3w2z5qtXamV7s9b/V3xr9'

govuk_mysql::server::expire_log_days: 1
govuk_mysql::server::innodb_file_per_table: true
govuk_mysql::server::slow_query_log: true

govuk::node::s_api_lb::api_servers:
  - "api-1.api"
  - "api-2.api"
govuk::node::s_api_lb::content_store_servers:
  - "content-store-1.api"
  - "content-store-2.api"
  - "content-store-3.api"
govuk::node::s_api_lb::draft_content_store_servers:
- "draft-content-store-1.api"
- "draft-content-store-2.api"
govuk::node::s_api_lb::email_campaign_api_servers:
  - "email-campaign-api-1.api"
  - "email-campaign-api-2.api"
  - "email-campaign-api-3.api"
govuk::node::s_api_lb::search_servers:
  - "search-1.api"
  - "search-2.api"
  - "search-3.api"
govuk::node::s_api_redis::allowed_api_ip_range: '10.2.4.0/24'
govuk::node::s_api_redis::allowed_backend_ip_range: '10.2.3.0/24'

govuk::node::s_asset_base::firewall_allow_ip_range: '10.2.3.0/24'
govuk::node::s_backend_lb::backend_servers:
  - 'backend-1.backend'
  - 'backend-2.backend'
  - 'backend-3.backend'
govuk::node::s_backend_lb::performance_backend_servers:
  - 'performance-backend-1.backend'
  - 'performance-backend-2.backend'
govuk::node::s_backend_lb::whitehall_backend_servers:
  - 'whitehall-backend-1.backend'
  - 'whitehall-backend-2.backend'
  - 'whitehall-backend-3.backend'
  - 'whitehall-backend-4.backend'
govuk::node::s_backend_lb::mapit_servers:
  - 'mapit-server-1.backend'
  - 'mapit-server-2.backend'
govuk::node::s_backend_lb::perfplat_public_app_domain: 'staging.performance.service.gov.uk'
govuk::node::s_cache::real_ip_header: 'True-Client-Ip'
govuk::node::s_frontend_lb::calculators_frontend_servers:
  - 'calculators-frontend-1.frontend'
  - 'calculators-frontend-2.frontend'
  - 'calculators-frontend-3.frontend'
govuk::node::s_frontend_lb::draft_frontend_servers:
  - 'draft-frontend-1.frontend'
  - 'draft-frontend-2.frontend'
govuk::node::s_frontend_lb::email_campaign_frontend_servers:
  - "email-campaign-frontend-1.frontend"
  - "email-campaign-frontend-2.frontend"
  - "email-campaign-frontend-3.frontend"
govuk::node::s_frontend_lb::frontend_servers:
  - 'frontend-1.frontend'
  - 'frontend-2.frontend'
  - 'frontend-3.frontend'
govuk::node::s_frontend_lb::performance_frontend_servers:
  - 'performance-frontend-1.frontend'
  - 'performance-frontend-2.frontend'
govuk::node::s_frontend_lb::performance_frontend_apps:
  - 'spotlight'
  - 'performanceplatform-big-screen-view'
govuk::node::s_frontend_lb::whitehall_frontend_servers:
  - 'whitehall-frontend-1.frontend'
  - 'whitehall-frontend-2.frontend'
  - 'whitehall-frontend-3.frontend'
  - 'whitehall-frontend-4.frontend'
  - 'whitehall-frontend-5.frontend'
  - 'whitehall-frontend-6.frontend'
  - 'whitehall-frontend-7.frontend'
govuk::node::s_graphite::enable_basic_auth: false
govuk::node::s_licensify_lb::licensify_backend_servers:
  - 'licensify-backend-1.licensify'
  - 'licensify-backend-2.licensify'
govuk::node::s_licensify_lb::licensify_frontend_servers:
  - 'licensify-frontend-1.licensify'
  - 'licensify-frontend-2.licensify'
govuk::node::s_licensify_mongo::licensify_mongo_encrypted: true
govuk::node::s_licensify_mongo::mongodb_backup_disk: '/dev/sdb1'
govuk::node::s_transition_postgresql_slave::redirector_ip_range: '10.2.5.0/24'

grafana::dashboards::machine_suffix_metrics: '_staging'

hosts::production::carrenza_vcloud: true
hosts::production::external_licensify: true
hosts::production::ip_api_lb: '10.2.4.254'
hosts::production::ip_backend_lb: '10.2.3.254'
hosts::production::ip_bouncer: '37.26.91.5'
hosts::production::ip_draft_api_lb: '10.2.4.253'
hosts::production::ip_frontend_lb: '10.2.2.254'
hosts::production::licensify_hosts:
  licensify.staging.publishing.service.gov.uk:
    ip: '37.26.91.8'
  licensify-admin.staging.publishing.service.gov.uk:
    ip: '37.26.91.8'

hosts::production::api::hosts:
  api-1:
    ip: '10.2.4.16'
  api-2:
    ip: '10.2.4.17'
  api-elasticsearch-1:
    ip: '10.2.4.25'
  api-elasticsearch-2:
    ip: '10.2.4.26'
  api-elasticsearch-3:
    ip: '10.2.4.27'
  api-lb-1:
    ip: '10.2.4.101'
  api-lb-2:
    ip: '10.2.4.102'
  api-mongo-1:
    ip: '10.2.4.21'
  api-mongo-2:
    ip: '10.2.4.22'
  api-mongo-3:
    ip: '10.2.4.23'
  api-mongo-4:
    ip: '10.2.12.21'
  api-postgresql-primary-1:
    ip: '10.2.4.40'
  api-postgresql-standby-1:
    ip: '10.2.4.41'
  api-postgresql-standby-2:
    ip: '10.2.12.41'
  api-redis-1:
    ip: '10.2.4.29'
  content-store-1:
    ip: '10.2.4.11'
  content-store-2:
    ip: '10.2.4.12'
  content-store-3:
    ip: '10.2.4.13'
  draft-content-store-1:
    ip: '10.2.4.200'
  draft-content-store-2:
    ip: '10.2.4.201'
  email-campaign-api-1:
    ip: '10.2.4.50'
  email-campaign-api-2:
    ip: '10.2.4.51'
  email-campaign-api-3:
    ip: '10.2.4.52'
  email-campaign-mongo-1:
    ip: '10.2.4.53'
  email-campaign-mongo-2:
    ip: '10.2.4.54'
  email-campaign-mongo-3:
    ip: '10.2.4.55'
  performance-mongo-1:
    ip: '10.2.4.31'
  performance-mongo-2:
    ip: '10.2.4.32'
  performance-mongo-3:
    ip: '10.2.4.33'
  performance-mongo-4:
    ip: '10.2.12.31'
  search-1:
    ip: '10.2.4.4'
  search-2:
    ip: '10.2.4.5'
  search-3:
    ip: '10.2.4.6'

hosts::production::backend::hosts:
  asset-master-1:
    ip: '10.2.3.20'
    legacy_aliases:
      - "asset-master-1.%{hiera('app_domain')}"
      - 'asset-master'
      - "asset-master.%{hiera('app_domain')}"
  asset-slave-1:
    ip: '10.2.3.21'
    legacy_aliases:
      - "asset-slave-1.%{hiera('app_domain')}"
      - 'asset-slave'
      - "asset-slave.%{hiera('app_domain')}"
  backend-1:
    ip: '10.2.3.2'
  backend-2:
    ip: '10.2.3.3'
  backend-3:
    ip: '10.2.3.4'
  backend-lb-1:
    ip: '10.2.3.101'
  backend-lb-2:
    ip: '10.2.3.102'
  elasticsearch-1:
    ip: '10.2.3.15'
  elasticsearch-2:
    ip: '10.2.3.16'
  elasticsearch-3:
    ip: '10.2.3.17'
  exception-handler-1:
    ip: '10.2.3.40'
  mapit-server-1:
    ip: '10.2.3.9'
  mapit-server-2:
    ip: '10.2.3.10'
  mongo-1:
    ip: '10.2.3.6'
    service_aliases:
      - 'mongodb'
  mongo-2:
    ip: '10.2.3.7'
  mongo-3:
    ip: '10.2.3.8'
  mongo-4:
    ip: '10.2.11.6'
  mysql-backup-1:
    ip: '10.2.3.93'
    legacy_aliases:
      - 'backup.mysql'
  mysql-master-1:
    ip: '10.2.3.90'
    legacy_aliases:
      - 'master.mysql'
      - "mysql.backend.%{hiera('internal_tld')}"
  mysql-slave-1:
    ip: '10.2.3.91'
    legacy_aliases:
      - 'slave.mysql'
  mysql-slave-2:
    ip: '10.2.3.92'
  mysql-slave-3:
    ip: '10.2.11.91'
  performance-backend-1:
    ip: '10.2.3.80'
  performance-backend-2:
    ip: '10.2.3.81'
  postgresql-primary-1:
    ip: '10.2.3.12'
  postgresql-standby-1:
    ip: '10.2.3.13'
  postgresql-standby-2:
    ip: '10.2.11.13'
  rabbitmq-1:
    ip: '10.2.3.70'
  rabbitmq-2:
    ip: '10.2.3.71'
  rabbitmq-3:
    ip: '10.2.3.72'
  redis-1:
    ip: '10.2.3.50'
  redis-2:
    ip: '10.2.3.51'
  transition-postgresql-master-1:
    ip: '10.2.3.60'
    legacy_aliases:
      - 'transition-master.postgresql'
      - "transition-postgresql.backend.%{hiera('internal_tld')}"
  transition-postgresql-slave-1:
    ip: '10.2.3.61'
    legacy_aliases:
      - 'transition-slave.postgresql'
  transition-postgresql-slave-2:
    ip: '10.2.11.61'
  whitehall-backend-1:
    ip: '10.2.3.25'
  whitehall-backend-2:
    ip: '10.2.3.26'
  whitehall-backend-3:
    ip: '10.2.3.27'
  whitehall-backend-4:
    ip: '10.2.3.28'
  whitehall-mysql-backup-1:
    ip: '10.2.3.34'
    legacy_aliases:
      - 'whitehall-backup.mysql'
  whitehall-mysql-master-1:
    ip: '10.2.3.30'
    legacy_aliases:
      - 'whitehall-master.mysql'
      - "whitehall-mysql.backend.%{hiera('internal_tld')}"
  whitehall-mysql-slave-1:
    ip: '10.2.3.31'
    legacy_aliases:
      - 'whitehall-slave.mysql'
  whitehall-mysql-slave-2:
    ip: '10.2.3.32'
  whitehall-mysql-slave-3:
    ip: '10.2.11.31'

hosts::production::frontend::hosts:
  calculators-frontend-1:
    ip: '10.2.2.11'
  calculators-frontend-2:
    ip: '10.2.2.12'
  calculators-frontend-3:
    ip: '10.2.2.13'
  frontend-1:
    ip: '10.2.2.2'
  frontend-2:
    ip: '10.2.2.3'
  frontend-3:
    ip: '10.2.2.4'
  draft-frontend-1:
    ip: '10.2.2.200'
  draft-frontend-2:
    ip: '10.2.2.201'
  email-campaign-frontend-1:
    ip: '10.2.2.30'
  email-campaign-frontend-2:
    ip: '10.2.2.31'
  email-campaign-frontend-3:
    ip: '10.2.2.32'
  performance-frontend-1:
    ip: '10.2.2.20'
  performance-frontend-2:
    ip: '10.2.2.21'
  whitehall-frontend-1:
    ip: '10.2.2.5'
  whitehall-frontend-2:
    ip: '10.2.2.6'
  whitehall-frontend-3:
    ip: '10.2.2.10'
  whitehall-frontend-4:
    ip: '10.2.2.14'
  whitehall-frontend-5:
    ip: '10.2.2.15'
  whitehall-frontend-6:
    ip: '10.2.2.16'
  whitehall-frontend-7:
    ip: '10.2.2.17'
  frontend-lb-1:
    ip: '10.2.2.101'
  frontend-lb-2:
    ip: '10.2.2.102'

hosts::production::management::hosts:
  jenkins-1:
    ip: '10.2.0.3'
  puppetmaster-1:
    ip: '10.2.0.5'
    legacy_aliases:
      - 'puppet'
    service_aliases:
      - 'puppet'
      - 'puppetdb'
  monitoring-1:
    ip: '10.2.0.20'
    legacy_aliases:
      - 'monitoring'
    service_aliases:
      - 'alert'
      - 'monitoring'
  graphite-1:
    ip: '10.2.0.22'
    legacy_aliases:
      - "graphite.%{hiera('app_domain')}"
    service_aliases:
      - 'graphite'
  logs-cdn-1:
    ip: '10.2.0.27'
  logging-1:
    ip: '10.2.0.28'
    service_aliases:
      - 'logging'
  logs-elasticsearch-1:
    ip: '10.2.0.29'
    service_aliases:
      - 'logs-elasticsearch'
  logs-elasticsearch-2:
    ip: '10.2.0.30'
  logs-elasticsearch-3:
    ip: '10.2.0.31'
  logs-redis-1:
    ip: '10.2.0.40'
  logs-redis-2:
    ip: '10.2.0.41'
  backup-1:
    ip: '10.2.0.50'
  etcd-1:
    ip: '10.2.0.60'
  etcd-2:
    ip: '10.2.0.61'
  etcd-3:
    ip: '10.2.0.62'
  apt-1:
    ip: '10.2.0.75'
    service_aliases:
      - 'apt'
  jumpbox-1:
    ip: '10.2.0.100'
  mirrorer-1:
    ip: '10.2.0.128'
  jumpbox-2:
    ip: '10.2.0.200'

hosts::production::redirector::hosts:
  bouncer-1:
    ip: '10.2.5.4'
  bouncer-2:
    ip: '10.2.5.5'
  bouncer-3:
    ip: '10.2.5.6'
  bouncer-4:
    ip: '10.2.13.4'
  bouncer-5:
    ip: '10.2.13.5'
  bouncer-6:
    ip: '10.2.13.6'

hosts::production::router::hosts:
  cache-1:
    ip: '10.2.1.2'
  cache-2:
    ip: '10.2.1.3'
  cache-3:
    ip: '10.2.1.4'
  draft-cache-1:
    ip: '10.2.1.200'
  draft-cache-2:
    ip: '10.2.1.201'
  router-backend-1:
    ip: '10.2.1.10'
  router-backend-2:
    ip: '10.2.1.11'
  router-backend-3:
    ip: '10.2.1.12'
  router-backend-4:
    ip: '10.2.9.10'
  cache:
    ip: '10.2.1.254'
    legacy_aliases:
      - 'cache'
      - "www.%{hiera('app_domain')}"
      - "www-origin.%{hiera('app_domain')}"
      - "assets-origin.%{hiera('app_domain')}"
    service_aliases:
      - 'cache'
      - 'router'
  router-backend-internal-lb:
    ip: '10.2.1.253'
    legacy_aliases:
      - "router-api.%{hiera('app_domain')}"
  draft-cache-internal-lb:
    ip: '10.2.1.252'
    legacy_aliases:
      - "draft-router-api.%{hiera('app_domain')}"

icinga::nginx::enable_basic_auth: false

#Do not enable this without speaking to Brad first
licensify::apps::licensing_web_forms::enabled: false

monitoring::checks::ses::region: eu-west-1

postfix::smarthost:
- 'email-smtp.us-east-1.amazonaws.com:587'
- 'ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com:587'
postfix::rewrite_mail_domain: 'digital.cabinet-office.gov.uk'
postfix::rewrite_mail_list: 'machine.email.carrenza'

postgresql_api_slave_addresses_live: '10.2.4.41/32'
postgresql_slave_addresses_live: '10.2.3.13/32'
postgresql_transition_slave_addresses_live: '10.2.3.61/32'
postgresql_transition_slave_addresses_dr: '10.2.11.61/32'

shell::shell_prompt_string: 'staging'

ssh::config::allow_users:
  - 'alexmuller'
  - 'alext'
  - 'benilovj'
  - 'bob'
  - 'bradleyw'
  - 'danielroseman'
  - 'davidsingleton'
  - 'deploy'
  - 'digitalassurancetester'
  - 'elliot'
  - 'govuk-backup'
  - 'jamiec'
  - 'jennyduckett'
  - 'joshmyers'
  - 'kushalp'
  - 'mattbostock'
  - 'paulmartin'
  - 'richardboulton'
  - 'robyoung'
  - 'stevelaing'
  - 'timothymower'
  - 'tombooth'
  - 'tommypalmer'

users::pentest_machines:
  - 'asset-master-1'
  - 'backend-1'
  - 'cache-1'
  - 'frontend-1'
  - 'jumpbox-1'
  - 'mysql-master-1'
  - 'postgresql-primary-1'

users::pentest_usernames:
  - digitalassurancetester

users::usernames:
  - alexmuller
  - alext
  - benilovj
  - bob
  - bradleyw
  - danielroseman
  - davidsingleton
  - elliot
  - jamiec
  - jennyduckett
  - joshmyers
  - kushalp
  - mattbostock
  - paulmartin
  - richardboulton
  - robyoung
  - stevelaing
  - timothymower
  - tombooth
  - tommypalmer
