---
app_domain: 'staging.publishing.service.gov.uk'

# Staging/production will not have separate internal load balancers until migrated to AWS
app_domain_internal: 'staging.publishing.service.gov.uk'

backup::server::backup_hour: 9

base::shell::shell_prompt_string: 'staging'
base::supported_kernel::enabled: false

cron::daily_hour: 6

environment_ip_prefix: '10.2'

govuk::apps::asset_manager::aws_s3_bucket_name: 'govuk-assets-staging'
govuk::apps::asset_manager::aws_region: 'eu-west-1'
govuk::apps::content_store::performance_platform_big_screen_view_url: 'https://performance-platform-big-screen-view-staging.cloudapps.digital'
govuk::apps::content_store::performance_platform_spotlight_url: 'https://performance-platform-spotlight-staging.cloudapps.digital'
govuk::apps::email_alert_api::db::backend_ip_range: '10.2.3.0/24'
govuk::apps::email_alert_api::govuk_notify_template_id: '2844a647-6bf1-4b01-a25c-569d2cc00849'
govuk::apps::email_alert_api::email_address_override: 'success@simulator.amazonses.com'
govuk::apps::email_alert_api::email_address_override_whitelist_only: true
govuk::apps::email_alert_api::delivery_request_threshold: "3000"
govuk::apps::hmrc_manuals_api::publish_topics: false
govuk::apps::kibana::logit_environment: d414187a-2796-4ea7-9b9a-d40c341646d6
govuk::apps::link_checker_api::govuk_basic_auth_credentials: "%{hiera('http_username')}:%{hiera('http_password')}"
govuk::apps::publicapi::backdrop_host: 'www.staging.performance.service.gov.uk'
govuk::apps::publisher::run_fact_check_fetcher: false
govuk::apps::publisher::fact_check_address_format: 'factcheck+staging-{id}@alphagov.co.uk'
govuk::apps::publishing_api::event_log_aws_bucketname: 'govuk-publishing-api-event-log-staging'
govuk::apps::short_url_manager::instance_name: 'staging'
govuk::apps::signon::instance_name: 'staging'
govuk::apps::support_api::pp_data_url: 'https://www.staging.performance.service.gov.uk'
govuk::apps::travel_advice_publisher::enable_email_alerts: true
govuk::apps::whitehall::cpu_warning: 400
govuk::apps::whitehall::cpu_critical: 600

govuk::deploy::aws_ses_smtp_host: 'email-smtp.eu-west-1.amazonaws.com'
govuk::deploy::config::errbit_environment_name: 'staging'
govuk::deploy::setup::ssh_keys:
    jenkins_staging_carrenza: 'AAAAB3NzaC1yc2EAAAADAQABAAACAQDCtuq8uMfbwh7asChk/F/VD5gPnnBD7pLeN1W4iOrkq3KbzdLErzK3W0EpCA2C07JU55egolaO7lDUF6MtmAiGLfHApju5lZ6ziUq+zebEbkwtpLUNop2zp51pZl5/meMEF9pQEcHD46iZGs1sLuZGNzzu12PKvpAHDFK9GPHrYez7asKh4JVCi5DNusOMFUFE+BW8w37zJZ4ksdeZ58w1PTS8+Q65k6MQdWDAUr9BLcsacZ2kzRHsMxP3bd3lljY9HT0lh1qPgwRcWqbfVjB8dAzTxiQHJm0w3xywcx/IUKMSL1WCJV7rZ5nt0XgOfU/cGRXDtRHPvMMrMfKqFGbyTTCjix4Y0k1FD2udXxvv03GjL12qohrsb1JxFv5CdLbV8Yn96IDIjEVKA+1GIwxl0w4TtMVCLqImIMaTD00tdY58fAb2uIy9xSTxu2jKdsEKCcbbC9ipE5lUM/3/kgl06OljBwgAcLgsbbWAHip59E3l6xO+BmW7f7PeepZMRDr15Xwr4RiEu76SQPoRFM5honi7yPLTNwscEgxEjZgKjOkNfVeABeJhJ5rOElAYx7K1bIsW/93DXtTWPDMxGGkiTM279Evy0LJjdVu6XGDmd9qw8usdKjfjASHe9mMFfSXZflHA6VW2o1Zjo40KWHXxJSdPN4bTujpahjd8QOb6Sw=='
    jenkins_production_carrenza: 'AAAAB3NzaC1yc2EAAAADAQABAAACAQCfPjubgzCkZo1aTPlkgeXb1eh3IonRBRptx0qLMCjOV+e+M8uRAT/Xx3ydJYPd7sOgZDyx2xjSGb7Eefau0jSUAcMD1Xd01SXWBQPJRDfPmQLrdbM0xxOFH8nft39uo4Mz6ccZc34xrudL6q/urp732HZHYwltnNnbk9h58n1QIhemRtN3u9RrSSOILqw/F42S6Aj8lZ1v/DGgfc6F5pKyJ7TByHL1RlqwpZHbEjYYuvK0ZJJsKPlyVPbNDsX7UEYWwbpPsFs9LPvCC6epmj+7Lv25bTU8rKK8J3rNWa1FybpWS0VXbF/+mrLjtT0/vwvbwUzsjK6dSUsbEsBEn+cOqomxCYkLjMzUy1+ReYAh6+CjmzutPs1g4OjQRel2ONprhPTEsNUu+oNObnGDOUpzHK10ntAZxguA4QEUmOBBWfxuQhmJO60/b1zedCcc7MR8e9S0y4jtpXa8GBCe40+napArZTW9QXlHLWz+khkYQfO107Q+z1QaLFojdcrHlUfpqAc6DtVJQu7tsBt2vXTn0qq6mU5Eg6UY+X1l/3gWdFS3ZEvCUoGK6bLU3i50jZ1xsFogFFfvSux46S1DYW2Fk8a/2IBBdcQcL1YoM73jiAQgpU8Vs50wtk4mWhK1yBaMYmMAeL7mKFbJla7SjTAwaDdo5uezyrJlbZxqTb/Y3w=='

# Staging never receives requests to bouncer
govuk_cdnlogs::bouncer_monitoring_enabled: false
# Increase the freshness-threshold for govuk logs as traffic is slower
govuk_cdnlogs::warning_cdn_freshness: 86400   # 1 day
govuk_cdnlogs::critical_cdn_freshness: 172800 # 2 days

govuk_crawler::seed_enable: true
govuk_crawler::sync_enable: true
govuk_crawler::targets:
  - 's3://govuk-mirror-staging/'

govuk_jenkins::config::banner_colour_background: '#ffbf47'
govuk_jenkins::config::banner_colour_text: 'black'
govuk_jenkins::config::banner_string: 'Carrenza STAGING'
govuk_jenkins::config::theme_colour: '#ffbf47'
govuk_jenkins::config::theme_text_colour: 'black'
govuk_jenkins::config::theme_environment_name: 'Staging'

govuk_elasticsearch::dump::run_es_dump_hour: '4'

govuk_jenkins::job_builder::environment: 'staging'

govuk_jenkins::jobs::network_config_deploy::environments:
  - 'carrenza-staging'
  - 'carrenza-staging-dr'
  - 'skyscape-staging'

govuk_jenkins::jobs::search_fetch_analytics_data::skip_page_traffic_load: true
govuk_jenkins::jobs::search_fetch_analytics_data::cron_schedule: '30 8 * * 1-5'
govuk_jenkins::jobs::smokey::smokey_task: 'test:staging'

govuk_jenkins::jobs::data_sync_complete_staging::signon_domains_to_migrate:
  -
    old: publishing.service.gov.uk
    new: staging.publishing.service.gov.uk
  -
    old: performance.service.gov.uk
    new: staging.performance.service.gov.uk
  -
    old: -production.cloudapps.digital
    new: -staging.cloudapps.digital

govuk_jenkins::jobs::deploy_dns::gce_client_name: 'govuk-dns-deploy'
govuk_jenkins::jobs::deploy_dns::gce_project_id: 'govuk-staging-160211'

govuk_jenkins::ssh_key::public_key: 'AAAAB3NzaC1yc2EAAAADAQABAAACAQDCtuq8uMfbwh7asChk/F/VD5gPnnBD7pLeN1W4iOrkq3KbzdLErzK3W0EpCA2C07JU55egolaO7lDUF6MtmAiGLfHApju5lZ6ziUq+zebEbkwtpLUNop2zp51pZl5/meMEF9pQEcHD46iZGs1sLuZGNzzu12PKvpAHDFK9GPHrYez7asKh4JVCi5DNusOMFUFE+BW8w37zJZ4ksdeZ58w1PTS8+Q65k6MQdWDAUr9BLcsacZ2kzRHsMxP3bd3lljY9HT0lh1qPgwRcWqbfVjB8dAzTxiQHJm0w3xywcx/IUKMSL1WCJV7rZ5nt0XgOfU/cGRXDtRHPvMMrMfKqFGbyTTCjix4Y0k1FD2udXxvv03GjL12qohrsb1JxFv5CdLbV8Yn96IDIjEVKA+1GIwxl0w4TtMVCLqImIMaTD00tdY58fAb2uIy9xSTxu2jKdsEKCcbbC9ipE5lUM/3/kgl06OljBwgAcLgsbbWAHip59E3l6xO+BmW7f7PeepZMRDr15Xwr4RiEu76SQPoRFM5honi7yPLTNwscEgxEjZgKjOkNfVeABeJhJ5rOElAYx7K1bIsW/93DXtTWPDMxGGkiTM279Evy0LJjdVu6XGDmd9qw8usdKjfjASHe9mMFfSXZflHA6VW2o1Zjo40KWHXxJSdPN4bTujpahjd8QOb6Sw=='

govuk_mysql::server::expire_log_days: 1
govuk_mysql::server::innodb_buffer_pool_size_proportion: '0.5'
govuk_mysql::server::slow_query_log: true

govuk::node::s_api_lb::api_servers:
  - "api-1.api"
  - "api-2.api"
govuk::node::s_api_lb::content_store_servers:
  - "content-store-1.api"
  - "content-store-2.api"
  - "content-store-3.api"
govuk::node::s_api_lb::draft_content_store_servers:
  - "draft-content-store-1.api"
  - "draft-content-store-2.api"
govuk::node::s_api_lb::mapit_servers:
  - "mapit-1.api"
  - "mapit-2.api"
govuk::node::s_api_lb::search_servers:
  - "search-1.api"
  - "search-2.api"
  - "search-3.api"

govuk::node::s_asset_master::copy_attachments_hour: 7

govuk::node::s_backend_lb::backend_servers:
  - 'backend-1.backend'
  - 'backend-2.backend'
  - 'backend-3.backend'
govuk::node::s_backend_lb::email_alert_api_backend_servers:
  - 'email-alert-api-1.backend'
  - 'email-alert-api-2.backend'
  - 'email-alert-api-3.backend'
govuk::node::s_backend_lb::performance_backend_servers:
  - 'performance-backend-1.backend'
  - 'performance-backend-2.backend'
govuk::node::s_backend_lb::publishing_api_backend_servers:
  - 'publishing-api-1.backend'
  - 'publishing-api-2.backend'
  - 'publishing-api-3.backend'
govuk::node::s_backend_lb::whitehall_backend_servers:
  - 'whitehall-backend-1.backend'
  - 'whitehall-backend-2.backend'
  - 'whitehall-backend-3.backend'
  - 'whitehall-backend-4.backend'
govuk::node::s_backend_lb::perfplat_public_app_domain: 'staging.performance.service.gov.uk'
govuk::node::s_cache::real_ip_header: 'True-Client-Ip'
govuk::node::s_frontend_lb::calculators_frontend_servers:
  - 'calculators-frontend-1.frontend'
  - 'calculators-frontend-2.frontend'
  - 'calculators-frontend-3.frontend'
govuk::node::s_frontend_lb::draft_frontend_servers:
  - 'draft-frontend-1.frontend'
  - 'draft-frontend-2.frontend'
govuk::node::s_frontend_lb::frontend_servers:
  - 'frontend-1.frontend'
  - 'frontend-2.frontend'
  - 'frontend-3.frontend'
govuk::node::s_frontend_lb::whitehall_frontend_servers:
  - 'whitehall-frontend-1.frontend'
  - 'whitehall-frontend-2.frontend'
  - 'whitehall-frontend-3.frontend'
  - 'whitehall-frontend-4.frontend'
  - 'whitehall-frontend-5.frontend'
  - 'whitehall-frontend-6.frontend'
  - 'whitehall-frontend-7.frontend'
govuk::node::s_monitoring::offsite_backups: false
govuk::node::s_mysql_backup::s3_bucket_name: 'govuk-mysql-xtrabackups-staging'
govuk::node::s_mysql_master::s3_bucket_name: "%{hiera('govuk::node::s_mysql_backup::s3_bucket_name')}"
govuk::node::s_whitehall_mysql_backup::s3_bucket_name: 'govuk-whitehall-mysql-xtrabackups-staging'
govuk::node::s_whitehall_mysql_master::s3_bucket_name: "%{hiera('govuk::node::s_whitehall_mysql_backup::s3_bucket_name')}"
govuk::node::s_transition_postgresql_slave::redirector_ip_range: '10.2.5.0/24'
govuk::node::s_transition_postgresql_standby::redirector_ip_range: "%{hiera('govuk::node::s_transition_postgresql_slave::redirector_ip_range')}"

govuk_postgresql::server::standby::pgpassfile_enabled: true

govuk_sudo::sudo_conf:
  deploy_service_postgresql:
    content: 'deploy ALL=NOPASSWD:/etc/init.d/postgresql'

grafana::dashboards::machine_suffix_metrics: '_staging'

hosts::production::ip_api_lb: '10.2.4.254'
hosts::production::ip_backend_lb: '10.2.3.254'
hosts::production::ip_bouncer: '37.26.91.5'
hosts::production::ip_draft_api_lb: '10.2.4.253'
hosts::production::ip_frontend_lb: '10.2.2.254'
hosts::production::licensify_hosts:
  licensify.staging.publishing.service.gov.uk:
    ip: '37.26.91.8'
  licensify-admin.staging.publishing.service.gov.uk:
    ip: '37.26.91.8'

hosts::production::api::hosts:
  api-1:
    ip: '10.2.4.16'
  api-2:
    ip: '10.2.4.17'
  api-lb-1:
    ip: '10.2.4.101'
  api-lb-2:
    ip: '10.2.4.102'
  api-mongo-1:
    ip: '10.2.4.21'
  api-mongo-2:
    ip: '10.2.4.22'
  api-mongo-3:
    ip: '10.2.4.23'
  api-mongo-4:
    ip: '10.2.12.21'
  api-redis-1:
    ip: '10.2.4.29'
  content-store-1:
    ip: '10.2.4.11'
  content-store-2:
    ip: '10.2.4.12'
  content-store-3:
    ip: '10.2.4.13'
  draft-content-store-1:
    ip: '10.2.4.200'
  draft-content-store-2:
    ip: '10.2.4.201'
  mapit-1:
    ip: '10.2.4.60'
  mapit-2:
    ip: '10.2.4.61'
  performance-mongo-1:
    ip: '10.2.4.31'
  performance-mongo-2:
    ip: '10.2.4.32'
  performance-mongo-3:
    ip: '10.2.4.33'
  performance-mongo-4:
    ip: '10.2.12.31'
  rummager-elasticsearch-1:
    ip: '10.2.4.55'
  rummager-elasticsearch-2:
    ip: '10.2.4.56'
  rummager-elasticsearch-3:
    ip: '10.2.4.57'
  search-1:
    ip: '10.2.4.4'
  search-2:
    ip: '10.2.4.5'
  search-3:
    ip: '10.2.4.6'

hosts::production::backend::hosts:
  asset-master-1:
    ip: '10.2.3.20'
    legacy_aliases:
      - "asset-master-1.%{hiera('app_domain')}"
      - 'asset-master'
      - "asset-master.%{hiera('app_domain')}"
  asset-slave-1:
    ip: '10.2.3.21'
    legacy_aliases:
      - "asset-slave-1.%{hiera('app_domain')}"
      - 'asset-slave'
      - "asset-slave.%{hiera('app_domain')}"
  asset-slave-2:
    ip: '10.2.11.21'
  backend-1:
    ip: '10.2.3.2'
  backend-2:
    ip: '10.2.3.3'
  backend-3:
    ip: '10.2.3.4'
  backend-lb-1:
    ip: '10.2.3.101'
  backend-lb-2:
    ip: '10.2.3.102'
  docker-backend-1:
    ip: '10.2.3.111'
  docker-backend-2:
    ip: '10.2.3.112'
  elasticsearch-1:
    ip: '10.2.3.15'
  elasticsearch-2:
    ip: '10.2.3.16'
  elasticsearch-3:
    ip: '10.2.3.17'
  email-alert-api-1:
    ip: '10.2.3.40'
  email-alert-api-2:
    ip: '10.2.3.41'
  email-alert-api-3:
    ip: '10.2.3.42'
  mongo-1:
    ip: '10.2.3.6'
    service_aliases:
      - 'mongodb'
  mongo-2:
    ip: '10.2.3.7'
  mongo-3:
    ip: '10.2.3.8'
  mongo-4:
    ip: '10.2.11.6'
  mysql-backup-1:
    ip: '10.2.3.93'
    legacy_aliases:
      - 'backup.mysql'
  mysql-master-1:
    ip: '10.2.3.90'
    legacy_aliases:
      - 'master.mysql'
      - "mysql.backend.%{hiera('app_domain')}"
  mysql-slave-1:
    ip: '10.2.3.91'
    legacy_aliases:
      - 'slave.mysql'
  mysql-slave-2:
    ip: '10.2.3.92'
  mysql-slave-3:
    ip: '10.2.11.91'
  performance-backend-1:
    ip: '10.2.3.80'
  performance-backend-2:
    ip: '10.2.3.81'
  postgresql-primary-1:
    ip: '10.2.3.12'
  postgresql-standby-1:
    ip: '10.2.3.13'
  postgresql-standby-2:
    ip: '10.2.11.13'
  publishing-api-1:
    ip: '10.2.3.45'
  publishing-api-2:
    ip: '10.2.3.46'
  publishing-api-3:
    ip: '10.2.3.47'
  rabbitmq-1:
    ip: '10.2.3.70'
  rabbitmq-2:
    ip: '10.2.3.71'
  rabbitmq-3:
    ip: '10.2.3.72'
  redis-1:
    ip: '10.2.3.50'
  redis-2:
    ip: '10.2.3.51'
  transition-postgresql-master-1:
    ip: '10.2.3.60'
    legacy_aliases:
      - 'transition-master.postgresql'
      - "transition-postgresql.backend.%{hiera('app_domain')}"
  transition-postgresql-slave-1:
    ip: '10.2.3.61'
    legacy_aliases:
      - 'transition-slave.postgresql'
  transition-postgresql-slave-2:
    ip: '10.2.11.61'
  transition-postgresql-primary-1:
    ip: '10.2.3.160'
  transition-postgresql-standby-1:
    ip: '10.2.3.161'
  transition-postgresql-standby-2:
    ip: '10.2.11.161'
  whitehall-backend-1:
    ip: '10.2.3.25'
  whitehall-backend-2:
    ip: '10.2.3.26'
  whitehall-backend-3:
    ip: '10.2.3.27'
  whitehall-backend-4:
    ip: '10.2.3.28'
  whitehall-mysql-backup-1:
    ip: '10.2.3.34'
    legacy_aliases:
      - 'whitehall-backup.mysql'
  whitehall-mysql-master-1:
    ip: '10.2.3.30'
    legacy_aliases:
      - 'whitehall-master.mysql'
      - "whitehall-mysql.backend.%{hiera('app_domain')}"
  whitehall-mysql-slave-1:
    ip: '10.2.3.31'
    legacy_aliases:
      - 'whitehall-slave.mysql'
  whitehall-mysql-slave-2:
    ip: '10.2.3.32'
  whitehall-mysql-slave-3:
    ip: '10.2.11.31'

hosts::production::frontend::hosts:
  calculators-frontend-1:
    ip: '10.2.2.11'
  calculators-frontend-2:
    ip: '10.2.2.12'
  calculators-frontend-3:
    ip: '10.2.2.13'
  frontend-1:
    ip: '10.2.2.2'
  frontend-2:
    ip: '10.2.2.3'
  frontend-3:
    ip: '10.2.2.4'
  draft-frontend-1:
    ip: '10.2.2.200'
  draft-frontend-2:
    ip: '10.2.2.201'
  whitehall-frontend-1:
    ip: '10.2.2.5'
  whitehall-frontend-2:
    ip: '10.2.2.6'
  whitehall-frontend-3:
    ip: '10.2.2.10'
  whitehall-frontend-4:
    ip: '10.2.2.14'
  whitehall-frontend-5:
    ip: '10.2.2.15'
  whitehall-frontend-6:
    ip: '10.2.2.16'
  whitehall-frontend-7:
    ip: '10.2.2.17'
  frontend-lb-1:
    ip: '10.2.2.101'
  frontend-lb-2:
    ip: '10.2.2.102'

hosts::production::management::hosts:
  jenkins-1:
    ip: '10.2.0.3'
    legacy_aliases:
      - "deploy.%{hiera('app_domain')}"
  puppetmaster-1:
    ip: '10.2.0.5'
    legacy_aliases:
      - 'puppet'
    service_aliases:
      - 'puppet'
      - 'puppetdb'
  monitoring-1:
    ip: '10.2.0.20'
    legacy_aliases:
      - 'monitoring'
      - "grafana.%{hiera('app_domain')}"
    service_aliases:
      - 'alert'
      - 'monitoring'
  graphite-1:
    ip: '10.2.0.22'
    legacy_aliases:
      - "graphite.%{hiera('app_domain')}"
    service_aliases:
      - 'graphite'
  logs-cdn-1:
    ip: '10.2.0.27'
  backup-1:
    ip: '10.2.0.50'
  apt-1:
    ip: '10.2.0.75'
    service_aliases:
      - 'apt'
      - 'gemstash'
  docker-management-1:
    ip: '10.2.0.80'
    service_aliases:
      - 'etcd'
  jumpbox-1:
    ip: '10.2.0.100'
  mirrorer-1:
    ip: '10.2.0.128'
  jumpbox-2:
    ip: '10.2.0.200'

hosts::production::redirector::hosts:
  bouncer-1:
    ip: '10.2.5.4'
  bouncer-2:
    ip: '10.2.5.5'
  bouncer-3:
    ip: '10.2.5.6'
  bouncer-4:
    ip: '10.2.13.4'
  bouncer-5:
    ip: '10.2.13.5'
  bouncer-6:
    ip: '10.2.13.6'

hosts::production::router::hosts:
  cache-1:
    ip: '10.2.1.2'
  cache-2:
    ip: '10.2.1.3'
  cache-3:
    ip: '10.2.1.4'
  draft-cache-1:
    ip: '10.2.1.200'
  draft-cache-2:
    ip: '10.2.1.201'
  router-backend-1:
    ip: '10.2.1.10'
  router-backend-2:
    ip: '10.2.1.11'
  router-backend-3:
    ip: '10.2.1.12'
  router-backend-4:
    ip: '10.2.9.10'
  cache:
    ip: '10.2.1.254'
    legacy_aliases:
      - 'cache'
      - "www.%{hiera('app_domain')}"
      - "www-origin.%{hiera('app_domain')}"
      - "assets-origin.%{hiera('app_domain')}"
    service_aliases:
      - 'cache'
      - 'router'
  router-backend-internal-lb:
    ip: '10.2.1.253'
    legacy_aliases:
      - "router-api.%{hiera('app_domain')}"
  draft-cache-internal-lb:
    ip: '10.2.1.252'
    legacy_aliases:
      - "draft-router-api.%{hiera('app_domain')}"

licensify::apps::licensify_admin::environment: 'staging'
licensify::apps::licensify::environment: 'staging'
licensify::apps::licensify_feed::environment: 'staging'
#Do not enable this without speaking to Tim Blair first
licensify::apps::licensing_web_forms::enabled: false

monitoring::checks::sidekiq::enable_support_check: false
monitoring::checks::ses::region: eu-west-1
monitoring::checks::smokey::environment: 'staging'
monitoring::uptime_collector::environment: 'staging'

postfix::smarthost:
  - 'email-smtp.us-east-1.amazonaws.com:587'
  - 'ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com:587'
postfix::rewrite_mail_domain: 'digital.cabinet-office.gov.uk'
postfix::rewrite_mail_list: 'machine.email.carrenza'

router::nginx::robotstxt: |
  User-agent: *
  Disallow: /

mongodb::s3backup::backup::s3_bucket: 'govuk-mongodb-backup-s3-staging'
mongodb::s3backup::backup::s3_bucket_daily: 'govuk-mongodb-backup-s3-daily-staging'
