publisher:             govuk_setenv publisher             ./run_in.sh ../publisher      bundle exec rails server -p 3000
imminence:             govuk_setenv imminence             ./run_in.sh ../imminence      bundle exec rails server -p 3002
panopticon:            govuk_setenv panopticon            ./run_in.sh ../panopticon     bundle exec rails server -p 3003
# needotron formerly used port 3004
frontend:              govuk_setenv frontend              ./run_in.sh ../frontend       bundle exec rails server -p 3005
# planner formerly used port 3007
rummager:              govuk_setenv search                ./run_in.sh ../rummager       bundle exec mr-sparkle --force-polling -- -p 3009
smartanswers:          govuk_setenv smartanswers          ./run_in.sh ../smart-answers  bundle exec rails server -p 3010
calendars:             govuk_setenv calendars             ./run_in.sh ../calendars      bundle exec rails server -p 3011
static:                govuk_setenv static                ./run_in.sh ../static         bundle exec rails server -p 3013
licencefinder:         govuk_setenv licencefinder         ./run_in.sh ../licence-finder bundle exec rails server -p 3014
migratorator:          govuk_setenv migratorator          ./run_in.sh ../migratorator   bundle exec unicorn -p 3015
signon:                govuk_setenv signon                ./run_in.sh ../signonotron2   bundle exec rails server -p 3016
tradetariff:           govuk_setenv tariff                ./run_in.sh ../trade-tariff-frontend   bundle exec rails server -p 3017
tradetariffapi:        govuk_setenv tariff-api            ./run_in.sh ../trade-tariff-backend  bundle exec rails server -p 3018
efg:                   govuk_setenv efg                   ./run_in.sh ../EFG            bundle exec rails server -p 3019
whitehall:             govuk_setenv whitehall    ./run_in.sh ../whitehall      bundle exec rails server -p 3020
reviewomatic:          ./run_in.sh ../review-o-matic bundle exec rails server -p 3021
reviewomaticexplore:   PORT=3023 ./run_in.sh ../review-o-matic-explore npm start
contentapi:            govuk_setenv contentapi            ./run_in.sh ../govuk_content_api bundle exec mr-sparkle --force-polling --pattern "rabl|rb|ru|txt|yml" -- -p 3022
designprinciples:      govuk_setenv designprinciples      ./run_in.sh ../design-principles bundle exec rails server -p 3023
businesssupportfinder: govuk_setenv businesssupportfinder ./run_in.sh ../business-support-finder bundle exec rails server -p 3024
# whitehall_search: uses port 3025
# whitehall_admin: uses port 3026
# datainsight-frontend used to use port 3027 but is no longer running in any environment
feedback:              govuk_setenv feedback              ./run_in.sh ../feedback       bundle exec rails server -p 3028
errbit:                govuk_setenv errbit                ./run_in.sh ../errbit         bundle exec rails server -p 3029
private-frontend:      govuk_setenv frontend              ./run_in.sh ../frontend       bundle exec rails server -p 3030
support:               govuk_setenv support               ./run_in.sh ../support        bundle exec rails s -p 3031
# publicapi:uses port 3032
# This will probably be renamed?
contracts-finder:      ./run_in.sh ../contracts-finder bundle exec rails server -p 3033
url-arbiter:           govuk_setenv url-arbiter           ./run_in.sh ../url-arbiter    bundle exec rails s -p 3034
travel_advice_publisher: govuk_setenv travel-advice-publisher ./run_in.sh ../travel-advice-publisher bundle exec rails s -p 3035
release:               govuk_setenv release               ./run_in.sh ../release        bundle exec rails server -p 3036
asset_manager:         govuk_setenv asset-manager         ./run_in.sh ../asset-manager  bundle exec rails s -p 3037
# limelight used port 3040 but was retired in November 2014
transaction_wrappers:  govuk_setenv transaction-wrappers  ./run_in.sh ../transaction-wrappers bundle exec unicorn -p 3041
# govuk_delivery has port 3042
# tariff_demo_api: grabbing port 3043 in preview only
transition:            govuk_setenv transition            ./run_in.sh ../transition     bundle exec rails s -p 3044
# tariff_demo: grabbing port 3045 in preview only
tariff_admin:          govuk_setenv tariff-admin          ./run_in.sh ../trade-tariff-admin bundle exec rails server -p 3046
calculators:           govuk_setenv calculators           ./run_in.sh ../calculators    bundle exec rails s -p 3047
# fact-cave used to use port 3048
bouncer:               govuk_setenv bouncer               ./run_in.sh ../bouncer        bundle exec mr-sparkle --force-polling -- -p 3049
fco_services:          ./run_in.sh ../fco-services bundle exec rails s -p 3050
hmrc_contacts:         govuk_setenv contacts              ./run_in.sh ../hmrc-contacts  bundle exec rails s -p 3051
need_api:              govuk_setenv need-api              ./run_in.sh ../govuk_need_api bundle exec rails s -p 3052
maslow:                govuk_setenv maslow                ./run_in.sh ../maslow         bundle exec rails s -p 3053
# router uses 3054 and 3055
router:                govuk_setenv router                ./run_in.sh ../router         make run
router-api:            govuk_setenv router-api            ./run_in.sh ../router-api     bundle exec rails s -p 3056
# alphagov/spotlight uses 3057 on CI ONLY (rest is Performance Platform infrastructure)
content_planner:       govuk_setenv content-planner       ./run_in.sh ../content-planner bundle exec rails s -p 3058
# alphagov/screenshot-as-a-service uses 3059
#                                  as well as 3060, but both only on CI (and Performance Platform boxes).
business_support_api:  govuk_setenv business-support-api  ./run_in.sh ../business-support-api bundle exec rails s -p 3061
finder-frontend:       govuk_setenv finder-frontend       ./run_in.sh ../finder-frontend bundle exec rails s -p 3062
finder-api:            govuk_setenv finder-api            ./run_in.sh ../finder-api     bundle exec mr-sparkle --force-polling -- -p 3063
specialist-publisher:  govuk_setenv specialist-publisher  ./run_in.sh ../specialist-publisher bundle exec foreman start
specialist-frontend:   govuk_setenv specialist-frontend   ./run_in.sh ../specialist-frontend bundle exec rails s -p 3065
# external-link-tracker uses 3066 and 3067
content-store:         govuk_setenv content-store         ./run_in.sh ../content-store  bundle exec rails s -p 3068
# content-store will also uses 3069
collections:           govuk_setenv collections           ./run_in.sh ../collections    bundle exec rails s -p 3070
hmrc-manuals-api:      govuk_setenv hmrc-manuals-api      ./run_in.sh ../hmrc-manuals-api bundle exec rails s -p 3071
manuals-frontend:      govuk_setenv manuals-frontend      ./run_in.sh ../manuals-frontend bundle exec rails s -p 3072
search-admin:          govuk_setenv search-admin          ./run_in.sh ../search-admin   bundle exec rails s -p 3073
contacts-frontend:     govuk_setenv contacts-frontend     ./run_in.sh ../contacts-frontend bundle exec rails s -p 3074
support-api:           govuk_setenv support-api           ./run_in.sh ../support-api    bundle exec rails s -p 3075
short-url-manager:     govuk_setenv short-url-manager     ./run_in.sh ../short-url-manager   bundle exec rails s -p 3076
# smartdown-frontend used to use port 3077, but is no longer running in any environment. hence, content-register took it over.
content-register:      govuk_setenv content-register      ./run_in.sh ../content-register  bundle exec rails s -p 3077
collections-publisher: govuk_setenv collections-publisher ./run_in.sh ../collections-publisher bundle exec rails s -p 3078
# sidekiq-monitoring uses 3079-3081 and 3086
service-manual:        govuk_setenv service-manual        ./run_in.sh ../government-service-design-manual  bundle exec unicorn -p 3082
# transition-postgres used to use port 3083, but is no longer running in any environment
collections-api:       govuk_setenv collections-api       ./run_in.sh ../collections-api bundle exec rails s -p 3084
info-frontend:         govuk_setenv info-frontend         ./run_in.sh ../info-frontend bundle exec rails s -p 3085
# sidekiq-monitoring for transition uses 3086
# metadata-api uses 3087
metadata-api:          govuk_setenv metadata-api          ./run_in.sh ../metadata-api make run
email-alert-api:       govuk_setenv email-alert-api       ./run_in.sh ../email-alert-api bundle exec foreman start
email-alert-service:   govuk_setenv email-alert-service   ./run_in.sh ../email-alert-service bundle exec bin/email_alert_service
# sidekiq-monitoring for email-alert-api uses 3089
government-frontend:   govuk_setenv government-frontend   ./run_in.sh ../government-frontend bundle exec rails s -p 3090
# sidekiq-monitoring for rummager uses 3091
courts-api:            govuk_setenv courts-api            ./run_in.sh ../courts-api bundle exec rails s -p 3092
publishing-api:        govuk_setenv publishing-api        ./run_in.sh ../publishing-api bundle exec rails s -p 3093

# datainsight-weekly-reach-recorder used to use port 3102, but is no longer running in any environment
# datainsight-todays-activity-recorder used to use port 3103, but is no longer running in any environment
# datainsight-format-success-recorder used to use port 3104, but is no longer running in any environment
# datainsight-everything-recorder used to use port 3105, but is no longer running in any environment
# datainsight-insidegov-recorder used to use port 3106, but is no longer running in any environment

# Frontend JS test runner uses port 3150
# Router test suite uses ports 3160-3169
# Firewall block rule on port 3170 (for testing connect timeouts)

# canary-frontend: doesn't currently use a port. reserved 3200
# canary-backend: doesn't currently use a port. reserved 3201
# kibana: reserved 3202
