# This Vagrantfile is dead.

$stderr.puts "[ERROR] This Vagrantfile is no longer current."
$stderr.puts ""
$stderr.puts "        You should run `vagrant up` in `../govuk-puppet/development` instead"
$stderr.puts ""
$stderr.puts "        Please see:"
$stderr.puts "        https://github.com/alphagov/govuk-puppet/blob/master/development/README.md"

exit 1
