# -*- mode: ruby -*-
# vi: set ft=ruby:

DIST_PREFERRED = :trusty
min_required_vagrant_version = '1.4.0'
DEFAULT_VM_PARAMS = {
  memory: 4096,
  cpus: 2,
}
BOXES = {
  virtualbox: {
    bucket: 'govuk-dev-boxes-test',
    latest_versions: {
      precise: '20160323',
      trusty: '20160323',
    },
  },
}

def common_config(config)
  # vagrant-dns is only supported on OS X
  # https://github.com/BerlinVagrant/vagrant-dns/blob/master/PLATFORM_SUPPORT.md
  if RUBY_PLATFORM =~ /darwin/i
    if Vagrant.has_plugin?("vagrant-dns")
      config.dns.tld = "dev.gov.uk"
      config.dns.patterns = [/^.*dev.gov.uk$/]
    else
      puts "installing vagrant-dns plugin is recommended"
    end
  end

  config.ssh.forward_agent = true

  config
end

def default_config(config)
  dist = (ENV['govuk_dev_dist'] or DIST_PREFERRED).to_sym
  if dist != DIST_PREFERRED
    puts <<EOS
[warn] Ubuntu version has been overridden with the environment variable
       `govuk_dev_dist` to a version other than "#{DIST_PREFERRED}". Please
       consider unsetting it.

EOS
  end

  default_box = "govuk_dev_#{dist}64_#{BOXES[:virtualbox][:latest_versions][dist]}"

  config.vm.box = default_box
  config.vm.box_url = "https://#{BOXES[:virtualbox][:bucket]}.s3.amazonaws.com/#{default_box}.box"
  # Static IP for NFS and DNS
  config.vm.network :private_network, :ip => "10.1.1.254"
  config.vm.hostname = "development.development"
  config.vm.provision :shell, :privileged => false, :inline => "NO_GIT_PULL=1 /var/govuk/govuk-puppet/tools/puppet-apply-dev"
  config.vm.provision :shell, :inline => "/usr/sbin/usermod -aG assets vagrant"
  config.vm.provision :file, source: "certs/auto_cert_config", destination: "auto_cert_config"
  config.vm.provision :shell, :path => "certs/generate_self_signed_certificate.sh"

  config
end

def load_local_vagrant_file(config)
  # Load local overrides
  if File.exist? 'Vagrantfile.local'
    $stderr.puts "WARNING: Vagrantfile.local is deprecated! Please use Vagrantfile.localconfig instead."
    $stderr.puts ""
  end

  if File.exist? 'Vagrantfile.localconfig'
    instance_eval File.read('Vagrantfile.localconfig'), 'Vagrantfile.localconfig'
  end

  config
end

def vagrant_version_at_least?(min_required_version)
  Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new(min_required_version)
end

unless vagrant_version_at_least?(min_required_vagrant_version)
  $stderr.puts "ERROR: Puppet now requires Vagrant version >=#{min_required_vagrant_version}. Please upgrade.\n"
  exit 1
end

Vagrant.configure("2") do |config|
  config = default_config(config)

  config.vm.provider :virtualbox do |vm, override|
    vm.customize ["modifyvm", :id, "--rtcuseutc", "on"]
    vm.customize [ "modifyvm", :id, "--memory", DEFAULT_VM_PARAMS[:memory], "--cpus", DEFAULT_VM_PARAMS[:cpus] ]
    if override.respond_to? :cache
      override.cache.auto_detect = true
    end
  end

  # Allow using native shared folders
  if ENV['VAGRANT_GOVUK_NFS'] == "no"
    config.vm.synced_folder "../..", "/var/govuk"
  else
    config.vm.synced_folder "../..", "/var/govuk", :type => :nfs
  end

  config = common_config(config)

  # You may want to change the memory or CPU number in the VM. Example given
  # below to put in Vagrantfile.localconfig if you want to do so - this sets
  # memory to 2048MB and the number of CPUs to 4.
  #
  #     config.vm.provider :virtualbox do |vm|
  #       vm.customize [ "modifyvm", :id, "--memory", "2048", "--cpus", "4" ]
  #     end

  config = load_local_vagrant_file(config)
end
