#!/bin/bash

# Use Let's Encrypt to generate a certificate for all the subdomains
# we are serving. This is required since the service.gov.uk domain
# enables HSTS.

MAIN_SITE="www.training.publishing.service.gov.uk"
SITE_LIST="`ls /etc/nginx/sites-enabled | grep training.publishing.service.gov.uk`"$'\n'"${MAIN_SITE}"
CS_SITE_LIST=`printf "${SITE_LIST}" | paste -s -d, -`
EMAIL="govuk-dev@digital.cabinet-office.gov.uk"
NGINX_CONF_DIR="/etc/nginx"
LETSENCRYPT_DIR="/etc/letsencrypt"

# Add repository and install certbot
sudo apt-get update -qq
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:certbot/certbot
sudo apt-get update -qq
sudo apt-get -y install certbot

# Certbot starts up its own webserver to perform the ACME protocol,
# so free up ports 80 and 443 by stopping nginx
sudo service nginx stop

# Run certbot to request the certificate
sudo certbot certonly --staging --cert-name ${MAIN_SITE} -m ${EMAIL} -n -d ${CS_SITE_LIST} --agree-tos --standalone

# Remove all the *.dev.gov.uk certificates that have been generated by
# puppet and replace them with symlinks to the Let's Encrypt certificate
rm -f ${NGINX_CONF_DIR}/ssl/*

while read -r LINE; do
    sudo ln -sf ${LETSENCRYPT_DIR}/live/${MAIN_SITE}/fullchain.pem ${NGINX_CONF_DIR}/ssl/${LINE}.crt
    sudo ln -sf ${LETSENCRYPT_DIR}/live/${MAIN_SITE}/privkey.pem ${NGINX_CONF_DIR}/ssl/${LINE}.key
done <<< "$SITE_LIST"

# Start nginx again so we serve everything
sudo service nginx start
