#!/bin/sh
set -e

# /usr/local/bin isn't in the path for cron by default
PATH=$PATH:/usr/local/bin
export PATH

MIRROR_ROOT=/var/lib/govuk_mirror
TMP_ROOT=$(mktemp -d -t govuk_mirror.XXXXX)

cleanup () {
  rm -rf "$LOCK"
  rm -rf "$TMP_ROOT"
}
trap cleanup EXIT

cd "$TMP_ROOT"

DEST="${MIRROR_ROOT}/$(date "+%Y%m%dT%H%M%S")"

# Mirror the site
govuk_mirrorer --logfile mirror.log

if [ ! "$(du -ks www.gov.uk | awk '{print $1}')" -gt "10000" ]; then
  echo "ERROR: Mirror appears to have failed (total size <10MB)" >> mirror.log
  echo "ERROR: Not updating 'current' symlink" >> mirror.log
  mv mirror.log "$DEST.log"
  exit 1
fi

mv mirror.log "$DEST.log"
mv www.gov.uk "$DEST"

# Clean up all but the last 7 mirror versions
find "$MIRROR_ROOT" -mindepth 1 -maxdepth 1 -type d |
  sort -r |
  tail -n +8 |
  while read dir; do
    rm -rf "$dir"
    rm "${dir}.log"
  done

# Update symlink to latest version
ln -snf "$DEST" "${MIRROR_ROOT}/current"

# Grab the error pages
for title in 404 406 410 418 500 503 504 ; do curl -sf https://static.production.alphagov.co.uk/templates/${title}.html.erb -o /var/lib/govuk_mirror/current/${title}.html; done
