#!/bin/bash
cd /tmp
rm -rf www.gov.uk
#Right now just copies only one file, for testing
/usr/bin/wget -v -mE -R licence-finder https://www.gov.uk
rm -rf /usr/share/www/www.gov.uk
mv www.gov.uk /usr/share/www/