#!/usr/bin/env ruby

require 'net/http'
require 'json'

API_ENDPOINT = 'https://www.gov.uk/api/artefacts.json'

FORMATS_TO_503 = %w(
  local_transaction
  smart-answer
  custom-application
  place
  licence
)

ADDITIONAL_WHITELIST_URLS = %w(
  https://www.gov.uk/designprinciples
  https://www.gov.uk/designprinciples/styleguide
  https://www.gov.uk/designprinciples/performanceframework
)

uri = URI.parse(API_ENDPOINT)
net = Net::HTTP.new(uri.host, uri.port)
net.use_ssl = (uri.scheme == 'https')

string = net.start {|req| req.get(uri.path).body }
data = JSON.parse(string)

whitelist = File.new('whitelist_urls', 'w')
blacklist = File.new('blacklist_paths', 'w')

data["results"].each do |artefact|
  if FORMATS_TO_503.include?(artefact["format"])
    blacklist.puts URI.parse(artefact["web_url"]).path
  else
    whitelist.puts artefact["web_url"]
  end
end

ADDITIONAL_WHITELIST_URLS.each do |url|
  whitelist.puts url
end

whitelist.close
blacklist.close
