#!/bin/sh
cat << EOS
This method of running Fabric is deprecated because it requires forwarding
your agent to the jumpbox. Anyone with root access to the jumpbox can re-use
any of the private keys in your agent.

Please use the local method instead:

https://github.com/alphagov/fabric-scripts#local-usage
EOS
exit 1
