---
app_domain: 'staging.publishing.service.gov.uk'
app_domain_internal: "staging.govuk-internal.digital"

backup::server::backup_hour: 9

base::shell::shell_prompt_string: 'staging'
base::supported_kernel::enabled: false

cron::daily_hour: 6

environment_ip_prefix: '10.12'

node_class: &node_class
  asset_master:
    apps:
      - asset_env_sync
  backend:
    apps:
      - transition
      - imminence
      - signon
  bouncer:
    apps:
      - bouncer
  cache:
    apps:
      - router
      - publicapi
  content_store:
    apps:
      - content-store
  calculators_frontend:
    apps:
      - calculators
      - calendars
      - finder-frontend
      - licencefinder
      - smartanswers
  ckan:
    apps:
      - ckan
  draft_cache:
    apps:
      - authenticating-proxy
      - router
      - router-api
      - draft-publicapi
  draft_content_store:
    apps:
      - content-store
  draft_frontend:
    apps:
      - collections
      - email-alert-frontend
      - frontend
      - government-frontend
      - manuals-frontend
      - service-manual-frontend
      - smartanswers
      - static
  email_alert_api:
    apps:
      - email-alert-api
      - email-alert-service
  frontend:
    apps:
      - canary-frontend
      - collections
      - email-alert-frontend
      - feedback
      - frontend
      - government-frontend
      - info-frontend
      - manuals-frontend
      - service-manual-frontend
      - static
  mapit:
    apps:
      - mapit
  mirrorer:
    apps:
      - govuk-crawler-worker
  publishing_api:
    apps:
      - publishing-api
  router_backend:
    apps:
      - router-api
  search:
    apps:
      - rummager
  whitehall_backend:
    apps:
      - whitehall
  whitehall_frontend:
    apps:
      - whitehall

govuk::node::s_base::node_apps:
  <<: *node_class

govuk_jenkins::deploy_all_apps::apps_on_nodes:
  <<: *node_class

govuk::apps::asset_manager::aws_s3_bucket_name: 'govuk-assets-staging'
govuk::apps::asset_manager::aws_region: 'eu-west-1'
govuk::apps::ckan::s3_bucket_name: "datagovuk-staging-ckan-organogram"
govuk::apps::ckan::s3_aws_region_name: "eu-west-1"
govuk::apps::content_data_admin::google_tag_manager_auth: 'xcAlGBhKTIeO6y_JhmEapQ'
govuk::apps::content_data_admin::google_tag_manager_id: 'GTM-NZG8SF2'
govuk::apps::content_data_admin::google_tag_manager_preview: 'env-5'
govuk::apps::content_publisher::aws_s3_bucket: "govuk-staging-content-publisher-activestorage"
govuk::apps::content_publisher::google_tag_manager_auth: "QaRG0YPL6_pwZdxCbyMXPQ"
govuk::apps::content_publisher::google_tag_manager_id: "GTM-NQXC4TG"
govuk::apps::content_publisher::google_tag_manager_preview: "env-5"
govuk::apps::content_store::performance_platform_big_screen_view_url: 'https://performance-platform-big-screen-view-staging.cloudapps.digital'
govuk::apps::content_store::performance_platform_spotlight_url: 'https://performance-platform-spotlight-staging.cloudapps.digital'
govuk::apps::email_alert_api::db::backend_ip_range: '10.12.3.0/24'
govuk::apps::email_alert_api::email_archive_s3_bucket: 'govuk-staging-email-alert-api-archive'
# This shouldn't be enabled at the same time we have carrenza s3 export enabled unless they have separate buckets
govuk::apps::email_alert_api::email_archive_s3_enabled: false
govuk::apps::email_alert_api::govuk_notify_template_id: '2844a647-6bf1-4b01-a25c-569d2cc00849'
govuk::apps::email_alert_api::email_address_override: 'success@simulator.amazonses.com'
govuk::apps::email_alert_api::email_address_override_whitelist_only: true
govuk::apps::email_alert_api::delivery_request_threshold: "3000"
govuk::apps::email_alert_frontend::subscription_management_enabled: true
govuk::apps::hmrc_manuals_api::publish_topics: false
govuk::apps::kibana::logit_environment: d414187a-2796-4ea7-9b9a-d40c341646d6
govuk::apps::link_checker_api::govuk_basic_auth_credentials: "%{hiera('http_username')}:%{hiera('http_password')}"
govuk::apps::publicapi::backdrop_host: 'www.staging.performance.service.gov.uk'
govuk::apps::publisher::run_fact_check_fetcher: false
govuk::apps::publisher::fact_check_address_format: 'factcheck+staging-{id}@alphagov.co.uk'
govuk::apps::publishing_api::event_log_aws_bucketname: 'govuk-publishing-api-event-log-staging'
govuk::apps::short_url_manager::instance_name: 'staging'
govuk::apps::signon::instance_name: 'staging'
govuk::apps::static::ga_universal_id: 'UA-26179049-20'
govuk::apps::support_api::pp_data_url: 'https://www.staging.performance.service.gov.uk'
govuk::apps::travel_advice_publisher::enable_email_alerts: true

govuk::deploy::aws_ses_smtp_host: 'email-smtp.eu-west-1.amazonaws.com'
govuk::deploy::config::errbit_environment_name: 'staging'
govuk::deploy::config::licensify_app_domain: 'staging.publishing.service.gov.uk'
govuk::deploy::setup::ssh_keys:
    jenkins_staging_carrenza: 'AAAAB3NzaC1yc2EAAAADAQABAAACAQDCtuq8uMfbwh7asChk/F/VD5gPnnBD7pLeN1W4iOrkq3KbzdLErzK3W0EpCA2C07JU55egolaO7lDUF6MtmAiGLfHApju5lZ6ziUq+zebEbkwtpLUNop2zp51pZl5/meMEF9pQEcHD46iZGs1sLuZGNzzu12PKvpAHDFK9GPHrYez7asKh4JVCi5DNusOMFUFE+BW8w37zJZ4ksdeZ58w1PTS8+Q65k6MQdWDAUr9BLcsacZ2kzRHsMxP3bd3lljY9HT0lh1qPgwRcWqbfVjB8dAzTxiQHJm0w3xywcx/IUKMSL1WCJV7rZ5nt0XgOfU/cGRXDtRHPvMMrMfKqFGbyTTCjix4Y0k1FD2udXxvv03GjL12qohrsb1JxFv5CdLbV8Yn96IDIjEVKA+1GIwxl0w4TtMVCLqImIMaTD00tdY58fAb2uIy9xSTxu2jKdsEKCcbbC9ipE5lUM/3/kgl06OljBwgAcLgsbbWAHip59E3l6xO+BmW7f7PeepZMRDr15Xwr4RiEu76SQPoRFM5honi7yPLTNwscEgxEjZgKjOkNfVeABeJhJ5rOElAYx7K1bIsW/93DXtTWPDMxGGkiTM279Evy0LJjdVu6XGDmd9qw8usdKjfjASHe9mMFfSXZflHA6VW2o1Zjo40KWHXxJSdPN4bTujpahjd8QOb6Sw=='
    jenkins_production_carrenza: 'AAAAB3NzaC1yc2EAAAADAQABAAACAQCfPjubgzCkZo1aTPlkgeXb1eh3IonRBRptx0qLMCjOV+e+M8uRAT/Xx3ydJYPd7sOgZDyx2xjSGb7Eefau0jSUAcMD1Xd01SXWBQPJRDfPmQLrdbM0xxOFH8nft39uo4Mz6ccZc34xrudL6q/urp732HZHYwltnNnbk9h58n1QIhemRtN3u9RrSSOILqw/F42S6Aj8lZ1v/DGgfc6F5pKyJ7TByHL1RlqwpZHbEjYYuvK0ZJJsKPlyVPbNDsX7UEYWwbpPsFs9LPvCC6epmj+7Lv25bTU8rKK8J3rNWa1FybpWS0VXbF/+mrLjtT0/vwvbwUzsjK6dSUsbEsBEn+cOqomxCYkLjMzUy1+ReYAh6+CjmzutPs1g4OjQRel2ONprhPTEsNUu+oNObnGDOUpzHK10ntAZxguA4QEUmOBBWfxuQhmJO60/b1zedCcc7MR8e9S0y4jtpXa8GBCe40+napArZTW9QXlHLWz+khkYQfO107Q+z1QaLFojdcrHlUfpqAc6DtVJQu7tsBt2vXTn0qq6mU5Eg6UY+X1l/3gWdFS3ZEvCUoGK6bLU3i50jZ1xsFogFFfvSux46S1DYW2Fk8a/2IBBdcQcL1YoM73jiAQgpU8Vs50wtk4mWhK1yBaMYmMAeL7mKFbJla7SjTAwaDdo5uezyrJlbZxqTb/Y3w=='

# Staging govuk traffic is so slow that the logs get rotated between
# checks, causing an alert because the expected file doesn't exist.
govuk_cdnlogs::govuk_monitoring_enabled: false
# Staging never receives requests to bouncer
govuk_cdnlogs::bouncer_monitoring_enabled: false

govuk_containers::terraboard::aws_bucket: 'govuk-terraform-steppingstone-staging'
govuk_containers::terraboard::oauth2_proxy_base_url: 'https://terraboard.staging.govuk.digital'

govuk_crawler::seed_enable: true
govuk_crawler::sync_enable: true
govuk_crawler::targets:
  - 's3://govuk-staging-mirror-1/'

govuk_elasticsearch::dump::run_es_dump_hour: '4'

govuk_jenkins::job_builder::environment: 'staging'

govuk_jenkins::jobs::network_config_deploy::environments:
  - 'carrenza-staging'
  - 'carrenza-staging-dr'
  - 'skyscape-staging'

govuk_jenkins::jobs::search_fetch_analytics_data::skip_page_traffic_load: true
govuk_jenkins::jobs::search_fetch_analytics_data::cron_schedule: '30 8 * * 1-5'

govuk_jenkins::jobs::smokey::environment: staging

govuk_jenkins::jobs::data_sync_complete_staging::signon_domains_to_migrate:
  -
    old: publishing.service.gov.uk
    new: staging.publishing.service.gov.uk
  -
    old: performance.service.gov.uk
    new: staging.performance.service.gov.uk
  -
    old: -production.cloudapps.digital
    new: -staging.cloudapps.digital

govuk_jenkins::jobs::deploy_dns::gce_client_name: 'govuk-dns-deploy'
govuk_jenkins::jobs::deploy_dns::gce_project_id: 'govuk-staging-160211'

govuk_jenkins::jobs::deploy_app::notify_release_app: false
govuk_jenkins::jobs::deploy_app::enable_slack_notifications: false

govuk_jenkins::ssh_key::public_key: 'AAAAB3NzaC1yc2EAAAADAQABAAACAQDCtuq8uMfbwh7asChk/F/VD5gPnnBD7pLeN1W4iOrkq3KbzdLErzK3W0EpCA2C07JU55egolaO7lDUF6MtmAiGLfHApju5lZ6ziUq+zebEbkwtpLUNop2zp51pZl5/meMEF9pQEcHD46iZGs1sLuZGNzzu12PKvpAHDFK9GPHrYez7asKh4JVCi5DNusOMFUFE+BW8w37zJZ4ksdeZ58w1PTS8+Q65k6MQdWDAUr9BLcsacZ2kzRHsMxP3bd3lljY9HT0lh1qPgwRcWqbfVjB8dAzTxiQHJm0w3xywcx/IUKMSL1WCJV7rZ5nt0XgOfU/cGRXDtRHPvMMrMfKqFGbyTTCjix4Y0k1FD2udXxvv03GjL12qohrsb1JxFv5CdLbV8Yn96IDIjEVKA+1GIwxl0w4TtMVCLqImIMaTD00tdY58fAb2uIy9xSTxu2jKdsEKCcbbC9ipE5lUM/3/kgl06OljBwgAcLgsbbWAHip59E3l6xO+BmW7f7PeepZMRDr15Xwr4RiEu76SQPoRFM5honi7yPLTNwscEgxEjZgKjOkNfVeABeJhJ5rOElAYx7K1bIsW/93DXtTWPDMxGGkiTM279Evy0LJjdVu6XGDmd9qw8usdKjfjASHe9mMFfSXZflHA6VW2o1Zjo40KWHXxJSdPN4bTujpahjd8QOb6Sw=='

govuk_mysql::server::expire_log_days: 1
govuk_mysql::server::innodb_buffer_pool_size_proportion: '0.5'
govuk_mysql::server::slow_query_log: true

govuk::node::s_asset_master::copy_attachments_hour: 7

govuk::node::s_cache::real_ip_header: 'True-Client-Ip'
# The option below can be changed to enable router to run as a container
govuk::node::s_cache::router_as_container: false
govuk::node::s_monitoring::offsite_backups: false

govuk_sudo::sudo_conf:
  deploy_service_postgresql:
    content: 'deploy ALL=NOPASSWD:/etc/init.d/postgresql'

grafana::dashboards::machine_suffix_metrics: '_staging'

licensify::apps::licensify_admin::environment: 'staging'
licensify::apps::licensify::environment: 'staging'
licensify::apps::licensify_feed::environment: 'staging'

monitoring::checks::sidekiq::enable_support_check: false
monitoring::checks::ses::region: 'eu-west-1'
monitoring::checks::rds::region: 'eu-west-1'
monitoring::checks::cache::region: 'eu-west-1'

# START OF TEMPORARY DEFECT FIX: # Smokey tests are not running correctly due to defects reported in: https://trello.com/c/XzGHhe3l/1629-investigate-cause-of-jenkins-oom-crashes-in-aws-staging-and-production
# monitoring::checks::smokey::environment: 'staging'
# END OF TEMPORARY DEFECT FIX

monitoring::uptime_collector::environment: 'staging'

postfix::smarthost:
  - 'email-smtp.us-east-1.amazonaws.com:587'
  - 'ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com:587'
postfix::rewrite_mail_domain: 'digital.cabinet-office.gov.uk'
postfix::rewrite_mail_list: 'machine.email.carrenza'

router::nginx::robotstxt: |
  User-agent: *
  Disallow: /

nginx::config::stack_network_prefix: '10.12.0'

govuk_datascrubber::ensure: 'latest'
govuk_datascrubber::share_with:
  - '210287912431'     # AWS integration
