# -*- mode: ruby -*-
# vi: set ft=ruby:

Vagrant.configure("2") do |config|

  config.vm.box = "dummy"
  config.vm.box_url="https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.keypair_name = "govuk-training-integration"
    aws.ami = "ami-a192bad2"
    aws.tags["Name"]= "training"
    aws.block_device_mapping = [ 
      {
        'DeviceName' => "/dev/sda1",
        'Ebs.VolumeSize' => 100,
        'Ebs.DeleteOnTermination' => true
      },
    ]
    aws.iam_instance_profile_name = ENV['AWS_IAM_INSTANCE_PROFILE_NAME']
    aws.region = ENV['AWS_REGION']
    aws.subnet_id = ENV['AWS_SUBNET']
    aws.instance_type = "t2.xlarge"
    aws.security_groups = ENV['AWS_SECURITY_GROUPS']
    aws.user_data = File.read("training_user_data.txt")

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = ENV['TRAINING_SSH_KEY_PATH']

    config.vm.synced_folder "provisioner", "/home/ubuntu", type: "rsync"
  end

end

