#!/bin/sh

#
# A simple wrapper around `puppet parser validate` to check for puppet syntax
# errors within a directory/directories.
# 

if [ $# -eq 0 ]; then
  echo "Usage: $(basename "$0") [dir [dir [...]]]" >&2
  exit 1
fi

status=$(mktemp -t puppet-syntax.XXXX)

trap "rm -f '$status'" EXIT

check_syntax () {
  find "$@" -name '*.pp' | xargs puppet parser validate
  echo "$?" >"$status"
}

check_syntax "$@" 2>&1 | grep -vF 'storeconfigs being set'

exit $(cat "$status")
