#!/bin/sh
set -e


TMPFILE=$(mktemp /tmp/hiera-temp-XXXXXX.yml)
echo "Creating temporary hiera config as $TMPFILE"
sed -e "s;^  :datadir: .*$;  :datadir: '/var/govuk/puppet/hieradata';g" /var/govuk/puppet/hiera.yml > $TMPFILE

# Filter warnings about 'storeconfigs' not being set
exec sudo \
  RBENV_VERSION=1.9.3 \
  /usr/bin/puppet apply /var/govuk/puppet/manifests/site.pp \
  --trusted_node_data \
  --environment ${ENVIRONMENT:-development} \
  --modulepath /var/govuk/puppet/modules:/var/govuk/puppet/vendor/modules \
  --hiera_config $TMPFILE "$@" 2>&1 \
  | egrep -iv --line-buffered "warning:.+storeconfigs"

rm $TMPFILE
