#!/bin/sh
set -e

# Filter warnings about 'storeconfigs' not being set
exec sudo \
  RBENV_VERSION=1.9.3 \
  /usr/bin/puppet apply /var/govuk/puppet/manifests/site.pp \
  --trusted_node_data \
  --environment ${ENVIRONMENT:-development} \
  --modulepath /var/govuk/puppet/modules:/var/govuk/puppet/vendor/modules \
  --hiera_config /var/govuk/puppet/hiera-puppetapply.yml "$@" 2>&1 \
  | egrep -iv --line-buffered "warning:.+storeconfigs"
