#!/bin/bash

# Set all the backups to be owned by the govuk-backup user
find /var/lib/autopostgresqlbackup -exec chown govuk-backup \{\} \;

# Allow others to download the latest backups
find /var/lib/autopostgresqlbackup/latest -exec chmod go+rw \{\} \;
