#!/bin/bash
ALLOWED_SEC_UPDATES=$1
ALLOWED_REG_UPDATES=$2
REG_UPDATES=`apt-get -ys upgrade | egrep '^Inst' | wc -l`
TOT_UPDATES=`apt-get -ys dist-upgrade | egrep '^Inst' | wc -l`
SEC_UPDATES=$(($TOT_UPDATES - $REG_UPDATES))
#echo $REG_UPDATES $SEC_UPDATES $TOT_UPDATES
if [ $SEC_UPDATES -gt $ALLOWED_SEC_UPDATES ]; then
  echo "CRITICAL: $SEC_UPDATES security updates need to be applied with 'apt-get dist-upgrade'"
  exit 2
elif [ $REG_UPDATES -gt $ALLOWED_REG_UPDATES ]; then
  echo "WARNING: $TOT_UPDATES package updates need to be applied with 'apt-get upgrade'"
  exit 1
else
  echo "OK: All packages up to date"
  exit 0
fi
