#!/bin/bash
# Replacement for Nagios check_apt, since it doesn't work:
# https://bugs.launchpad.net/ubuntu/+source/nagios-plugins/+bug/1031680
set -eu

ALLOWED_SEC_UPDATES=$1

OUTPUT=$(/usr/lib/update-notifier/apt-check 2>&1)
SEC_UPDATES=$(echo $OUTPUT | cut -d\; -f2)

if [ $SEC_UPDATES -gt $ALLOWED_SEC_UPDATES ]; then
  echo "CRITICAL: ${SEC_UPDATES} security updates need to be applied with 'apt-get dist-upgrade'"
  exit 2
else
  echo "OK: All security updates applied"
  exit 0
fi
