#!/usr/bin/env python2
import string
import subprocess
import sys

class CheckException(Exception):
    def __init__(self, message, severity):
        Exception.__init__(self, message)
        self.severity = severity


def nagios_message(message, exitcode):
    """Format a Nagios message and exit"""
    print message
    sys.exit(exitcode)


def nagios_ok(message):
    """Nagios OK message"""
    raise CheckException("OK: %s" % message, 0)


def nagios_warning(message):
    """Nagios WARNING message"""
    raise CheckException("WARNING: %s" % message, 1)


def nagios_critical(message):
    """Nagios CRITICAL message"""
    raise CheckException("CRITICAL: %s" % message, 2)


def parse_apt_get(security_updates, critical, warning):
    if security_updates > critical:
        nagios_critical("%s security updates have not been installed automatically"
                        % security_updates)
    elif security_updates > warning:
        nagios_warning("%s security updates have not been installed automatically"
                       % security_updates)
    else:
        nagios_ok("All security updates applied")


usage_message = """
Usage: check_apt_security_updates [critical] [warning]

Checks the number of outstanding security updates

When given no arguments, the default threshold is 0 updates.
One argument will raise a critical alert at that number of updates.
Two arguments will raise a warning at the first number of updates
and a critical at the second number of updates
"""


def main():
    try:
        if len(sys.argv) >= 3:
            warning = int(sys.argv[2])
            critical = int(sys.argv[1])
        elif len(sys.argv) == 2:
            if sys.argv[1] == "-h":
                print usage_message
                sys.exit(0)
            else:
                warning = int(sys.argv[1])
                critical = int(sys.argv[1])
        else:
            warning = 0
            critical = 0

        proc = subprocess.Popen(["/bin/bash", "-c", "apt-get upgrade -s | grep -i security | wc -l"],
                                stdout=subprocess.PIPE,
                                stderr=subprocess.STDOUT)
        apt_get_output = int(proc.stdout.read())
        parse_apt_get(apt_get_output, critical, warning)

    except CheckException as e:
        nagios_message(e.message, e.severity)
    except Exception as e:
        # Catching all other exceptions
        nagios_message("Exception: %s" % e, 3)

if __name__ == '__main__':
    main()
